### ISSUE TITLE
Non-serious errors blocking events queue (PP)

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/MoodleDirectV2#109]
We're seeing the Moodle events queue being blocked by things that Turnitin counts as "errors" but which should probably result in the event being discarded rather than attempting to retry it indefinitely.

The main one is "Your submission must contain 100 characters or more", which appears to happen where someone submits, for example, an Excel document with charts but no text. I would expect this to be ignored rather than blocking the queue, particularly given that there's not much anyone can do to change it!

Other examples are:
- "Your submission could not be processed"
- "Your submission does not contains valid text"
- "Your submission must contain 20 words or more"

This is for 2014012408 of the plugin, but the code in `plagiarism_plugin_turnitin::tii_submission()` seems to be there in 2014012409 too.

I understand that there is potential for serious error messages to be returned, so it might not be sensible to return true for all errors, and also that there are no error codes returned from the API, but expected operational rejections shouldn't be able to block the queue. Only serious, temporary failures at the Turnitin end should result in retry requests.

**Comment by Syxton** [comment]
We seem to be seeing a similar issue right now on version 2014012412.  It is filling our cron queue.

**Comment by jmcgettrick** [comment]
Hi @Syxton, what are the error messages you're receiving?

**Comment by Syxton** [comment]
Ok, we have figured out what it was.  A student uploaded a file with a question mark in it. (Either using a Mac or did a Moodle "Save file as".  When I attempted it, it crashed the tab, failed to upload to Turnitin, then made an event in events_queue that cron couldn't complete, so events were stacking up behind it.

**Comment by Syxton** [comment]
No, the file name.  Using the plagiarism plugin, on an assignment.  Although the title might also have this issue.  I guess I should have specified.

**Comment by brendanheywood** [comment]
We experienced something very similar a couple days ago where the the queue backed up. It looked like the student had submitted a file which they then later removed, that cron process was just sitting there with the task lock open for 24+ hours doing nothing. We ended up just killing that cron process and it continued on fine after.
