### ISSUE TITLE
Turnitin Grademark doesn't appear to observe the visibility of the activity's grade item

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#113]
Reading through the code for get_links() I can't find anywhere that checks if the grade item for the activity (or the grade_grade item for the user's attempt at the activity) is visible or not.

It would look like the grademark link is displayed to the student based on lots of things *other* than this.

Our users tend to use the ability to hide grade items as a way to embargo access to grades. The use of the hiddenuntil option for a grade item allows this to now be scheduled, but the PP doesn't appear to check either {{hidden}} or {{hiddenuntil}} before deciding whether or not the display the grademark link...

**Comment by jmcgettrick** [comment]
Thanks Michael, this has been fixed and is in the latest release.
