### ISSUE TITLE
Submission Filenames

### ISSUE THREAD

**Issue by sk-unikent** [jmcgettrick/MoodleDirectV2#122]
We have had a request come in, complaining about the filenames that lecturers get when downloading submissions.
They would find it easier if the student's username was part of the filename for example.
Having looked at the kind of filename they currently get, it is rather nasty:
37288358-_mnt_cl-moodle-nfs_moodle2014data_temp_turnitintooltwo_1780496815._test

I was wondering if you'd be able to add an option for filename formats?
We'd at least like to have the username of the user pushed to the front, and ideally have it use a filename rather than a fullpath.

**Comment by jmcgettrick** [comment]
We've changed the filenames to be a bit more user friendly in the latest release - 2014012413.
