### ISSUE TITLE
Is the Plagiarism Plugin trying to do too much?

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#123]
Following on from what is now our 5th week of issues with TII, I have a thought that the plagiarism plugin is doing too much work and not in a "moodley" way:

1)
>Grademark and Peermark tools are configured and launched from the plugin and accessed via the plagiarism "area" of the page. There is already a "grade" option (provided by Moodle), so this is adding a 2nd, alternative mechanism and can cause confusion over which option users should choose.

Grademark (& possibly Peermark) should move to being a Moodle Advanced grading method. This would mean that the tool launches via the "grade" icon on the submission table.

2)
>The get_links() function which is meant to integrate plagiarism system is about 500 lines long. This is for a function that gets called for at once on the assignment "overview" page, and for **every** submission on the grading table.

`get_links()` should short and fast, it should do as little processing as possible and (only) load information from the local moodle database (so no php / curl brokered calls etc).

Also the originality score and report "could" be exposed via a Feedback plugin rather than being in the file submission area, which may allow for additional features like being able to sort by originality score.

3)
>The `get_links()` function is also loading up javascript which then causes TII to do updates/refreshes, with (in my mind) not much value being added (also since it's using jQuery this fires before the YUI moodle javascript and prevents the Moodle javascript running until it's finished talking to TII).

All of the process of submitting a file to TII should be done via the cron. When a user uploads a file, a plugin table should record this, and set a status indicating it's pending (i.e. not yet uploaded). `get_links()` can then report this status quickly without any further checks. Once it is uploaded by the cron the status can change to "uploaded" (with the TII paper ID if necessary written in to the DB record). When the a report is generated and the cron job fetches it, the score and status are written into the record for `get_links()` to display.

Also with the 2.7 code introducing the new scheduling tasks the ability for the cron task to check for updates from Turnitin can run at a **much** faster rate, and for most cases the information does not have to be "real time".

In all cases the fetching / updating is disconnected from the UI.

**Comment by mattgibson** [comment]
+1

get_links() in particular is proving to be problematic as it is doing so many things (multiple calls per user to the turnitin api) and is really slowing the page load down for me. It should really only be reading from the Moodle DB and displaying what it finds.

**Comment by brendanheywood** [comment]
+1

**Comment by cwestgarth** [comment]
@mhughes2k @mattgibson @brendanheywood 

Thanks for the feedback.

I appreciate that the different workflows for Moodle and Turnitin can cause confusion, particularly when it comes to grading and dates. It would not feasible, from a business point of view, for us to separate or remove Turnitin functionality from the plugin. 

We do recognise that the get_links() function is rather large and we will look at refactoring it. There are certain aspects we will have to retain, both for functionality and from a legal standpoint, e.g. Document viewer launchers and our EULA.

The submission process could also be improved and we will look at streamlining it in to fit in more with Moodle’s workflow.

**Comment by mhughes2k** [comment]
I can appreciate you may not want to go in to the business points of view as to why you can't separate the launching of the document viewer in to an advanced grading method plugin, but I'm struggling to see the disadvantages of it from an end-user's perspective...

The actual implementation costs of this is not significant, especially if you consider that 
1. mod_turnitintooltwo already consolidates the majority of the comms protocol with Turnitin and the DV launching and 
2. is being leveraged by the plagiarism plugin and
3. You've already got a number of separate plugins and 
4. It's *not* talking about doing *anything* new, just hooking the existing TII features to more appropriate Moodle hooks...(i.e. wiring up the "grade" button to the TII DV)

**Comment by cwestgarth** [comment]
Hi @mhughes2k,
I will investigate this further to see if it technically possible.

**Comment by jmcgettrick** [comment]
Hi @mhughes2k, with v2015040109 we've removed the instant submitting from the plagiarism plugin so get_links has been simplified. All submissions are now processed by the cron. It's still very long but it is an ongoing project to refactor it and get it shortened.

You made another point about viewing rubrics. That has been released already as well.

Thanks
