### ISSUE TITLE
Cron Error

### ISSUE THREAD

**Issue by JeryH** [jmcgettrick/MoodleDirectV2#129]
Since updating to 2014012410 running on Moodle 2.7.2 we are seeing errors in cron:

Trying to get property of non-object in /moodle/plagiarism/turnitin/lib.php on line 1425

This was not happening in a previous version we were advised to take from from GitHub by TurnItIn.

**Comment by jmcgettrick** [comment]
Thanks, this has been fixed and is in the latest release. We no longer use gradeitem if it doesn't exist.
