### ISSUE TITLE
Cannot disable Grademark for plagiarism plugin

### ISSUE THREAD

**Issue by aspark21** [jmcgettrick/MoodleDirectV2#135]
Hi John,

We want to be able to use grademark on the standalone mod/turnitintooltwo however we need to be able to disable the Grademark option when we use the TII plagiarism plugin in other tools.

I thought this was already an option but it doesn't seem to be the case.

As a side note, We also want to be able to use the anonymous option when grademark is disabled for the  plagiarism plugin route.

**Comment by jmcgettrick** [comment]
Hi, apologies for the delay in replying. 

Long term the configuration settings will be split out in to the plagiarism plugin but it isn't a priority for us at the moment as institutions would have to duplicate a lot of settings. The Grademark link is only available to instructors unless a submission has been graded via GradeMark so at least students will not be to access it if it's not used.

Anonymous marking is a Grademark feature so can't be separated out, you could use the blind marking setting in a Moodle assignment though. That is completely separate from Turnitin functionality.
