### ISSUE TITLE
Unit Tests Fail on plagiarism

### ISSUE THREAD

**Issue by azrek** [jmcgettrick/MoodleDirectV2#136]
Running unit tests fails on /plagiarism/turnitin/lib.php (line 225) due to a bug in the SQL.  

To re-run:
 vendor/bin/phpunit tool_uploadcourse_course_testcase admin/tool/uploadcourse/tests/course_test.php

Debugging: Exception encountered in event observer 'plagiarism_plugin_turnitin::course_reset': Error reading from database (ERROR:  column turnitin_assignid does not exist
LINE 6:                     AND ptc.name = turnitin_assignid
                                           ^
SELECT cm.id
                    FROM phpu_course_modules cm
                    RIGHT JOIN phpu_plagiarism_turnitin_config ptc ON cm.id = ptc.cm
                    WHERE cm.module = 
                    AND cm.course = 
                    AND ptc.name = turnitin_assignid
[array (
  0 => '1',
  1 => 2,
)])

In PostGres, the double quotes used to delimit the string is interpreted as a column.

It should be wrapped in single quotes:
            $sql = 'SELECT cm.id
                    FROM {course_modules} cm
                    RIGHT JOIN {plagiarism_turnitin_config} ptc ON cm.id = ptc.cm
                    WHERE cm.module = :moduleid
                    AND cm.course = :courseid
                    AND ptc.name = \'turnitin_assignid\'';

Thanks.

**Comment by jmcgettrick** [comment]
Thanks, this has been fixed and is in the latest release.
