### ISSUE TITLE
Cron function to keep the max submission size within Turnitin's limit (PP)

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#137]
Not a bug but it helps to minimize the number of rejected submissions for us:
https://github.com/lucisgit/MoodleDirectV2/commit/df25851583697cc06008028300f331035a86f06f

Just in case someone finds it useful.

**Comment by jmcgettrick** [comment]
Thanks Tony. We'll add this to a "other contributions" page for the next release.
