### ISSUE TITLE
Error Handling seems Futile

### ISSUE THREAD

**Issue by tworthington** [jmcgettrick/MoodleDirectV2#138]
v2014012410

In edit_tii_assignment (for example, there are many others), there is a try..catch block. The catch is:

 catch (Exception $e) {
            $turnitincomms->handle_exceptions($e, 'editassignmenterror');
        }

But handle_exceptions() simply ends up calling  turnitintooltwo_print_error($errorstr, null); which in turn calls the core print_error() which then throws a new Moodle exception, at which point we're outside of any local try...catch block and the result is that the error is unhandled and, in our case, the whole cron task collapses with an error message again.

I really think you need a try...catch around the whole of the cron function in the plagarism/turnitin/lib.php file at the least; around each function call inside that would be even better.

**Comment by jmcgettrick** [comment]
The latest release changed error handling slightly. Exceptions no longer kill the cron, the errors that are caught are now output to the screen.
