### ISSUE TITLE
Pop ups being block but no dialog to allow them appearing

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#140]
We are seeing issues where accessing the matched sources in the document viewer is not working.

It would appear that the iframe in which the document viewer is loaded is using the "sandbox" attribute but it is not providing the "allow-popup" attribute. 

![pop-up block 2](https://cloud.githubusercontent.com/assets/694841/5527575/76d6f03c-89f7-11e4-8a1d-abb078d268df.JPG)

![pop-up block](https://cloud.githubusercontent.com/assets/694841/5527574/7254eaaa-89f7-11e4-8108-feb1b5ad1929.JPG)

**Comment by jmcgettrick** [comment]
Hi Michael, this has been fixed and is now in the latest release.
