### ISSUE TITLE
Cron persistently checks for null OverallSimilarity values

### ISSUE THREAD

**Issue by alexumn** [jmcgettrick/MoodleDirectV2#141]
Related to Dominic's note at https://github.com/jmcgettrick/MoodleDirectV2/commit/80ab23e32dde5f7d7c4d20ad7006304ddb757e6e#commitcomment-9113710, we continue to have a problem with the cron. 

A large number of Moodle assignments have Turnitin enabled, but the PP settings are not set to compare against anything in particular, so "Generate Originality Reports for submissions?" is set to NO for the assignments on Turnitin.com. The number of submissions in this state is very large (12,000+), which is far more than the Turnitin API's 500 response limit, the list of results to check for is never reduced, so the next time the cron runs, it still checks for details of 12,000+ submissions. So, the stack of results to check for never decreases.

This means that when a submission is made and an originality score is generated by Turnitin, there are 12,000 submissions in front of that same submission, so the originality score for submissions does not appear in the UI.

**Comment by jmcgettrick** [comment]
Hi Alex, this is now in the latest release.
