### ISSUE TITLE
Need to have all the module specific code in the plagiarism plugin in separate classes

### ISSUE THREAD

**Issue by mattgibson** [jmcgettrick/MoodleDirectV2#165]
At the moment, there are lots of places in the code where there is a switch statement that does different stuff depending on the module type of the assignment/forum/workshop being submitted. This makes it almost impossible to integrate the plugin with third party modules.

A better approach would be to have a class for each module, which can either be included with this plugin (for the three default core modules that are supported), or auto loaded in the case of third party modules. Something like:

```
$classname = $modname.'_turnitin'
if (class_exists($classname) {
    $modfunctions = new $classname($this);
    $modfunctions->callback_function();
}
```

If a structure could be agreed in principle, I would be happy to do the work and make a pull request with the existing module-specific code ported to the new structure.

**Comment by jmcgettrick** [comment]
Hi Matt, apologies for the delay in responding but I'll follow this up with you via email.
