### ISSUE TITLE
(PP) plagiarism_turnitin_files table needs an index on externalid

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/MoodleDirectV2#167]
There are a couple of queries in the plagiarism plugin that are looking up a record in the plagiarism_turnitin_files table by externalid, but this field isn't indexed so it's having to do a full table scan every time. An index on externalid would massively reduce the amount of server resources being used to process these queries.

**Comment by jmcgettrick** [comment]
This has been added for 2014012413 and is now released.
