### ISSUE TITLE
Turnitin Assignment Inbox

### ISSUE THREAD

**Issue by isomaa** [jmcgettrick/MoodleDirectV2#192]
Moodle: Moodle 2.5.2+ (Build: 20131101)

Turnitin: V2 2014012403

When posting a score of zero for a student in a Turnitin assignment, the zero does not appear in the grade column. The same double dashes that were displayed in the grade column before grading remain there. This gives the impression that the activity was not graded. Version 1 Turnitin tool actually displayed a zero in the grade column. Is there a way to have V2 show a "0" in the grade column?

Thanks

**Comment by jmcgettrick** [comment]
Hi, this is an issue we are aware of and will get fixed as soon as possible.

**Comment by isomaa** [comment]
Hi, has this been fixed yet?

Thanks,
Aaron

**Comment by jmcgettrick** [comment]
Hi Aaron, this issue has been fixed but it's not a plugin issue so we are currently waiting for an internal release.

**Comment by jmcgettrick** [comment]
This has now been fixed and should work without a plugin upgrade.
