### ISSUE TITLE
Error adding turnitin assignment

### ISSUE THREAD

**Issue by CamBanfield** [jmcgettrick/MoodleDirectV2#204]
When trying to add a Turnitin two assignment, the following error message is displayed:

turnitintooltwo/There was an error when trying to get the user details from Turnitin

File: [dirroot]/mod/turnitintooltwo/sdk/soap.class.php | Line: 257 | Message: SOAP-ERROR: Parsing WSDL: Couldn't load from '[dirroot]/mod/turnitintooltwo/sdk/wsdl/lis-membership.wsdl' : failed to load external entity "[dirroot]/mod/turnitintooltwo/sdk/wsdl/lis-membership.wsdl" | Code: 0

Moodle version: Moodle 2.7.3+ (Build: 20141211)
Turnitin version: 2014012411

**Comment by jmcgettrick** [comment]
Hi Cam,
It seems that your Moodle environment can't parse the WSDL file. Can you try adding the following line to your moodle config.php: libxml_disable_entity_loader(false);
We've had a similar problem reported in the past and Dan Marsden provided this information.
John

**Comment by aspark21** [comment]
This is an issue with External Entities see #71.

@jmcgettrick did add it to the troubleshooting here - https://github.com/jmcgettrick/MoodleDirectV2/blob/master/TROUBLESHOOTING.md

**Comment by jmcgettrick** [comment]
Thanks aspark21! Let us know if that works Cam.

**Comment by CamBanfield** [comment]
Thanks! That did the trick :-)

I'll close this report
