### ISSUE TITLE
API Updating Password

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#207]
John,

This is more of a request to be kept updated on an existing bug.

One of our users reported to the TII help desk that their password kept being changed, and got the following response back:

(Turnitin Help Desk Case #00366731 - 2434 University of Strathclyde    [ ref:_00D30H14._50040gkkJm:ref ])
> The engineer overseeing your case provided some feedback. 
> He explained that it looks like this is an issue with the API. It looks like the API is generating a random password EVERY time the user is updated and the "user_password" field is not sent with the request. (Hopefully we don't expect the customer to send the unencrypted password along with every request). Given the comment above in sub validate_user_password "# If they try to update a user's password, throw error.  A user password can only be set on user creation and it should not be able to be modified."
> The password should not be updated. This is probably only a problem for users who use an integration AND access Turnitin native website for users who never log in through native won't notice that their password is being changed every time their user is updated.

We use the Plagiarism plugin for just about all interactions (really save for admins) so it would be good to be able to track this issue's state...but it's a bit unclear if he means the problem is with the API, the mod or the PP plugin.

Currently it means I'm having to trigger a password reset almost every time I want to access the TII admin interfaces...

**Comment by jmcgettrick** [comment]
This has been fixed now with version 2015010407. We've also added the ability for a student to view a rubric before they submit to a Moodle assignment which if I remember correctly, you'd asked for.
