### ISSUE TITLE
Support for Submit on behalf for Plagiarism Plugin

### ISSUE THREAD

**Issue by aspark21** [jmcgettrick/MoodleDirectV2#227]
We would like to be able to use Submit on Behalf for other Moodle Tools through the Plagiarism Plugin, however the PP doesn't allow this and keeps overwriting a submission as being from the submitter rather than the specified student.

**Comment by mhughes2k** [comment]
I'm not sure that I understand what you're asking to be supported? This or your other suggestion #228 either...

**Comment by aspark21** [comment]
There is a "Submit on behalf" function on the TII V2 Assignment so that an admin can submit the file for the student, however this is not available to third party plugins through the plagiarism plugin. @mattgibson can probably elaborate on the actual code for this as he has tried to work on this for a plugin and hit a dead end.

**Comment by mattgibson** [comment]
The problem I ran into was to do with the javascript attempting to submit the work with the teacher's userid when the similarity report was shown, right after the teacher had submitted work on behalf of a student (implemented by firing the assessable_files_uploaded event with the student id and having stored the files with the student id). There seem to be a lot of assumptions about the code running within the Turnitin mod, so it's hard to reuse in other places.

What's really needed is for a lot of the code scattered through the plagiarism plugin to be factored out into classes which are specific to the module that is submitting the file, leaving the main plugin a lot slimmer.

**Comment by mhughes2k** [comment]
ahh..right I understand better now.The problem is that Moodle up until 2.7 (apparently) hasn't ever supported the notion of submission on behalf of another user. 

This is however apparently a new 2.7 capability that can be turned on, so on this basis I'd presume that the TII plagiarism plugin would simply continue what it's doing (uploading whatevers in the submission record to TII), whilst Moodle handles the fact that some else (who's not the actual owner of the record) has modified the submission's files.

**Comment by mattgibson** [comment]
Yes, that's what I was hoping for.

This is in a third party mod, BTW, not in the core assignment tool. I ran into quite a few places where there are if/else statements that switch on the module name scattered through the plagiarism plugin, so it's been quite awkward to work around these as the code is assuming a lot.

**Comment by mhughes2k** [comment]
Yep, just confirmed that the Edit Other Student submission capability does what is says on the tin, and allows staff to change the submission files contents.

I'd assume (and @jmcgettrick could maybe confirm) that the TII PP would simply use the student's identity (after all the submission record is theirs), and that it will just *work*...

**Comment by jmcgettrick** [comment]
@mhughes2k it would use whichever value is passed as userid from the Plagiarism API. I'd need to check but I believe this is the original submitter's id.

**Comment by mattgibson** [comment]
I'll have to have another look into the code and see exactly where, but the passing in of the userid definitely gets stuck right now.

A related issue is that the tutor then gets asked to accept the Turnitin EULA (on behalf of the student) instead of seeing the similarity report.

**Comment by jmcgettrick** [comment]
We've added this into v2015040109
