### ISSUE TITLE
PP does not take assignment marking workflow states into account: patch to manipulate post dates

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#237]
Moodle 2.6 introduced the concept of marking workflow and allocation to the assignment module (mod_assign). Currently the plagiarism_turnitin plugin doesn't seem to contain any logic to support this functionality, so as we use it quite extensively here our teachers have been reporting inconsistent behaviour in Turnitin-enabled assignments.

As a result I've been having to add marking workflow support into the PP as and when these issues have come to light. This patch deals with the release of TII Grademark feedback: https://github.com/lucisgit/MoodleDirectV2/commit/b3f49201d243c84eb292e622f3c96adc1cb55090

Initially this just prevented the grademark icon being displayed to the student until after the marking workflow state was changed to 'released', however we then realised that students were still able to access their feedback via similarity reports and logging into Turnitin directly, so the patch now includes code to manipulate the post date depending on the workflow state too.

Issue https://github.com/jmcgettrick/MoodleDirectV2/issues/238 includes a patch to prevent Grademark grades being pushed to the Moodle gradebook before release.

**Comment by jmcgettrick** [comment]
Thanks for this Tony, I've commited this code with a few modifications, mostly to check for Moodle version. See: https://github.com/jmcgettrick/MoodleDirectV2/pull/423

**Comment by jmcgettrick** [comment]
This has been released in 2015040105.
