### ISSUE TITLE
PP does not take assignment marking workflow states into account: patch to prevent grades being passed to gradebook before release date

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#238]
Following on from issue https://github.com/jmcgettrick/MoodleDirectV2/issues/237, this patch prevents grades from Grademark being written to the Moodle gradebook before the marking workflow status for the assignment has been changed to 'released': https://github.com/lucisgit/MoodleDirectV2/commit/4d4a881c1d68239159299317acc4ae565f0dfae6

Moodle itself includes a function that copies the grade and feedback to the gradebook when it is eventually released.

**Comment by jmcgettrick** [comment]
Thanks for this Tony, I've commited this code with a slight modification to check for Moodle version. https://github.com/jmcgettrick/MoodleDirectV2/commit/7d16ef30e060bde81b460b117369c18c6b1c846f

**Comment by jmcgettrick** [comment]
This has been released in 2015040105.
