### ISSUE TITLE
PP does not update grades edited by a teacher directly within a Moodle assignment

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#240]
If a teacher grades an assignment via Grademark, the awarded grade is then copied into the assignment grading table in Moodle. However if the teacher then inadvertently edits the grade directly within the Moodle activity, the grade from Grademark will not revert it, even if the DV is launched and closed again. The only way to trigger Grademark to overwrite it is to launch the DV and actually change the grade in Grademark again. This is because the grade has not been altered in the plagiarism_turnitin_files table, only in the activity grades table, so the function that updates the grades from Grademark cannot detect that a change has been made.

This patch modifies the update_grade_from_tii() function to take into account the grade from the activity table when deciding whether the Moodle grade needs an update. It also includes a cron task to check for Moodle grades needing an update from Grademark on a regular schedule (see issue https://github.com/jmcgettrick/MoodleDirectV2/issues/239): https://github.com/lucisgit/MoodleDirectV2/commit/74b01e811d68a499304e9e6bc916b249d6b5e068

**Comment by jmcgettrick** [comment]
Closing as this has been followed up via email.

Thanks for the input again Tony.

**Comment by tonyjbutler** [comment]
John, this issue has not been resolved and a resolution is very much needed. I have merely been informed that my patch results in too much additional load on the Turnitin servers. I will continue to work on it.

Please re-open. Thanks.
