### ISSUE TITLE
Service Limitations

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#261]
@jmcgettrick would it be possible to get some sort of documentation on the service limits that are enforced by turnitin

I've tried looking at the TII website and there is *no* technical documentation (it also says that 2014012403 is the version released...).

I get questions about:
* Number of resubmissions permitted to students
* Service call limits (maximum number of submissions that can be passed in, calls per minute etc, any throttling that is applied)
* Turn around speed (it would be nice if there was some quality of service metrics available, e.g. originality reports taking approximately [15min|1.5 hrs|broken]

**Comment by jmcgettrick** [comment]
Hi Michael, 
Resubmissions are unlimited up until the due date from a student but they can only submit once after the due date has passed. That is why we continually have to move the due date forward in the plagiarism plugin.
Turnaround speeds depend on server load but are usually fairly quick (ie a few seconds to a minute), however resubmissions can take up to 24 hours.
As for service call limits, I've forwarded your query on to our product team and will get back to you when I hear back. 
Thanks
John

**Comment by mhughes2k** [comment]
The issue we current have is students getting:
![image](https://cloud.githubusercontent.com/assets/694841/6368657/a1484a0c-bcd6-11e4-8a5b-0c65fa7afa5f.png)

The message doesn't appear to be coming from within the plugin from what we can tell...

**Comment by jmcgettrick** [comment]
Sorry, my answers were for Turnitin in general. The plagiarism plugin will only attempt to send a submission 5 times, this was added to stop constantly attempting to submit the same file if Turnitin wouldn't accept it. There should be an error in the API logs to explain that particular submission being rejected.

**Comment by mhughes2k** [comment]
John, 

Just looking at the code for ````tii_submission()```, and I can see that it limits the number of times it will send to TII to 5 at the start, but the exception handling later on appears to increment the number of attempts irrespective of the cause of failure.

The error message also sounds more like it limits the number of attempts that the user can make (against the activity), rather than attempts to send it to turnitin...

Also I've not found any occurrences of the string "There has been an error with your submission" (which maps to the en translation of "pp_submission_error") in our cron log or the turnitin API logs.

**Comment by mhughes2k** [comment]
Also we've found the Plagiarism plugin error report is showing:
![image](https://cloud.githubusercontent.com/assets/694841/6440951/9042f2ae-c0da-11e4-9854-77fe800c0d1c.png)

**Comment by jmcgettrick** [comment]
I suspect these could be connected issues. Turnitin will only accept submissions that contain at least 100 characters or 20 words, unless "Allow submission of any file type?" is set to Yes.

Does 'This file does not have enough content for Turnitin to produce an Originality Report.' appear in your cron as this is the error we return in this instance?

**Comment by mhughes2k** [comment]
Nope, can't find any occurrences of that error message in our cron logs at all...

**Comment by jmcgettrick** [comment]
Does the error occur in the API logs? 
Do the API logs contain any submission responses with similar errors?
Is the error occurring for a number of users with different files?

**Comment by mhughes2k** [comment]
With regard to the 5 attempts..what happens during Turnitin downtime? Events will still be raised by Moodle, but presumably if the TII end point isn't responding this counts as a failed attempt?

**Comment by jmcgettrick** [comment]
There is a test connection in the cron which returns false if there is no connection so the event would not be processed. It was added in 2014012409.

**Comment by mhughes2k** [comment]
A related question to the 5 attempts message, I can see that this check has been in since April 2014, but it only recently seems to have been coming to light to users recently. 

It appears that we've had users who have submitted items with less than the minimum content, and they're getting this message instead of the one that says they've provided insufficient number of words...

**Comment by mhughes2k** [comment]
John, 

We just got a completely incorrect response (well if we go with your version) to this very question about the 5 attempts:

Turnitin Help Desk Case #00399229
> Thank you for contacting the Turnitin Help Desk.
> It seems that in this case the Moodle submission settings are to allow only a maximum of 5 attempts.
> If a student is allowed to resubmit, this setting will determine how many times they can resubmit before they are no longer allowed to do so.
> This is a Moodle setting, please have the Instructor to verify the submission settings and verify the maximum attempts allowed.
> If you need additional assistance with this case please reply to this email. 
 > For future support convenience, we invite you to visit our new [1]Turnitin Self-Service Help Center for quick answers to your questions.   

It would appear that your support desk don't actually know how the plagiarism plugin is working..

**Comment by amclarty** [comment]
If you can let us know your setup I can try and replicate the issues you're having. It'd be useful to know assignment settings, the number of times students are submitting, when they experience these errors, etc.

Please post any API and Activity Log errors you are receiving and the version of Moodle and the plugin you have installed.

**Comment by mhughes2k** [comment]
HI @amclarty *This isn't an issue with the set up*, it is an issue with contradictory information being passed out from Turnitin.

@jmcgettrick has said that this message is generated when the plagiarism plugin has attempted to send a submitted file to the TII service 5 times and the TII service has rejected 5 times (taking into account that there is a check to ensure that the service is available).

Your help desk colleague (who you can identify from the help case #) then responds to a support query saying that this is a Moodle setting, which it isn't.

The Moodle activity in question is *not* making use of any re-attempts, the students may submit as many times as they wish up to the due date, and the *only* place that a limitation of 5 attempts appears is: 
````
public function tii_submission($cm, $tiiassignmentid, $user, $identifier, $submissiontype, $itemid = 0,
                                    $title = '', $textcontent = '', $context = 'instant') {
        global $CFG, $DB, $USER;
        $settings = $this->get_settings($cm->id);
        $nooffilesallowed = $this->get_max_files_allowed($cm->instance, $cm->modname);
        // Do not submit if 5 attempts have been made previously.
        $previoussubmissions = $DB->get_records_select('plagiarism_turnitin_files',
                                        " cm = ? AND userid = ? AND submissiontype = ? AND identifier = ? ",
                                    array($cm->id, $user->id, $submissiontype, $identifier), 'id, attempt');
        $previoussubmission = current($previoussubmissions);
        $attempt = (empty($previoussubmission)) ? 0 : $previoussubmission->attempt;
        if (count($previoussubmissions) >= 5 || $attempt >= 5) {
            if ($context == 'cron') {
                mtrace('-------------------------');
                mtrace(get_string('pastfiveattempts', 'turnitintooltwo').':');
                mtrace('User:  '.$user->id.' - '.$user->firstname.' '.$user->lastname.' ('.$user->email.')');
                mtrace('Course Module: '.$cm->id.'');
                mtrace('-------------------------');
                return true;
            }
            $return["success"] = false;
            $return["message"] = get_string('pastfiveattempts', 'turnitintooltwo');
            return $return;
        }
````
https://github.com/jmcgettrick/MoodleDirectV2/blob/master/plagiarism/turnitin/lib.php#L2166

I can appreciate that this may not be something that is in your control to improve their understanding of how your product works, but their knowledge appears to be severely lacking (both with regard to this plugin, how it works with Moodle and Moodle in general). We shall be feeding this back to your help desk colleagues as well.

It does feel that the effort being put in by the development side (which is appreciated) is being undermined by the support side, who are the primary point of contact for most queries.

**Comment by jmcgettrick** [comment]
I suspect there's been a misunderstanding and the confusion has been around the resubmission rules in Turnitin. We'll liaise with the help desk and work on improving this aspect of the support for our Moodle plugins.
