### ISSUE TITLE
More informing error messages

### ISSUE THREAD

**Issue by DaGhostman** [jmcgettrick/MoodleDirectV2#264]
A few days ago I was configuring the plugin with Moodle 2.8.x and experienced a big issue, which took me about a day to resolve.

When entering the TII API URL, whenever I clicked the 'Test Turnitin Connection' button, to check if a connection could be made to the URL provided, I was receiving 'Unable to connect, check URL and/or credentials' (Excuse me, if I am mistaken the error message), which doesn't help at all, nor gives any idea on where to start troubleshooting.

It turned out, the issue was with my PHP configuration, there was no entry for the [curl.cainfo](http://php.net/manual/en/curl.configuration.php#ini.curl.cainfo).

Solution 1:
----
If you could add:
`curl_setopt($ch, CURLOPT_CAINFO, 'path-to-ca-file.crt');`

It will fix the issues, but will require adding the [ca-bundle.crt from here](https://github.com/bagder/ca-bundle/) in the plugin directory.

Solution 2
----
Make the call output more information, which mioght help trouble shoot configuration issues, `curl_error()` output might be helpful. If you are concerned about non-technical users seeing 'strange-voodoo-words' show the curl output if debugging is enabled. 

NOTE: The second solution might work with the error codes in [this comment](http://php.net/manual/en/function.curl-errno.php#103128), the one in question is [60].

**Comment by jmcgettrick** [comment]
Hi, we'll look into this.

**Comment by DaGhostman** [comment]
Will be highly appreciated

**Comment by DaGhostman** [comment]
Well, if the server does not have root CA configured, the connection will fail, as curl wouldn't be able to verify the certificate of the server relative lines are [286](https://github.com/jmcgettrick/MoodleDirectV2/blob/master/mod/turnitintooltwo/sdk/soap.class.php#L286) and [287](https://github.com/jmcgettrick/MoodleDirectV2/blob/master/mod/turnitintooltwo/sdk/soap.class.php#L287), where curl defines that the PEER and HOST should be verified.

If the certificate is not defined curl will error in something like: `[60] error setting certificate verify locations: CAfile: /usr/share/ssl/certs/ca-bundle.crt CApath: none` which is totally unrelated to to the user's credentials.

**Comment by jmcgettrick** [comment]
To do this we would have to modify the SDK used by the plugin. This could have knock on effects for other integrations which use the SDK so we'll need to scope it out further and consider the impact before implementing this.
