### ISSUE TITLE
Moodle administrators should have instructor access to all courses on turnitin.com

### ISSUE THREAD

**Issue by alexumn** [jmcgettrick/MoodleDirectV2#280]
Moodle administrators need to be able to troubleshoot integration issues between Moodle activities (assignments, forums, and workshops) that have the Turnitin Plagiarism Prevention Plugin enabled, and the equivalent "Moodle PP" courses and assignments on turnitin.com. However, who has access to what turnitin.com course is not consistent:

1. One user is an administrator in our Moodle 2.6 production instance and has instructor access to 1,676 Turnitin courses in our production Turnitin account.
2. Another user is an administrator in the same Moodle instance and has instructor access to 1,021 Turnitin courses.
3. A third user is also a Moodle admin, but has access to no courses in Turnitin. When that user logs in, he is prompted me for a class id and password, both of which are required. There is no "change role to instructor" option in the upper right, only {"Currently not logged in", Languages, "Roadmap", "Help"}

For #1 and #2, we have opened Turnitin support ticket 00401331 which includes who has access to what.

**Comment by jmcgettrick** [comment]
Hi Alex, we currently only mass enrol users as Turnitin instructors at the point when the class is first created in Turnitin - see create_tii_course() in lib.php. So, if a class was created before a new administrator was added to a Moodle environment they would not be enrolled. 

The only other point where we enrol instructors is when a user with the relevant permissions opens the Document Viewer or Peermark Manager.

**Comment by alexumn** [comment]
Thanks John. We're looking into making it so Moodle administrators will be given instructor access to all Moodle PP courses on Turnitin.com for the associated Turnitin account.

It seems like overkill, but hooking that into cron might be the simplest way to trigger the process.

**Comment by jmcgettrick** [comment]
Ok Alex, let us know how you get on.
