### ISSUE TITLE
$plugin->version and upgrade_plugin_savepoint differ

### ISSUE THREAD

**Issue by porcospino** [jmcgettrick/MoodleDirectV2#287]
In version.php you have $plugin->version = 2014012413, but in db/upgrade.php you call upgrade_plugin_savepoint(true, 2015012413, 'plagiarism', 'turnitin');

Next time you visit your site as an administrator, you will get the following error:

"Cannot downgrade plagiarism_turnitin from 2015012413 to 2014012413."

You need to change $plugin-version in version.php to match the version you've upgraded to.

**Comment by jmcgettrick** [comment]
Hi, thanks. This won't pose any issues for this release but it means we'll be starting afresh with new version numbers for the next release.

**Comment by fluxcorenz** [comment]
This was an issue when updating moodle to 2.8.5 - it wouldn't continue due to the plugin 'downgrade'. Manually editing the version.php file allowed the upgrade to proceed.

**Comment by jmcgettrick** [comment]
I've updated the version number in master to be 2015012413. We'll sync them up again with next release.
