### ISSUE TITLE
'Section error' for plagiarism plugin

### ISSUE THREAD

**Issue by daparker26** [jmcgettrick/MoodleDirectV2#293]
In Moodle (v2.6.6), when I try to access the settings page for the Turnitin plagiarism plugin (Plugins->Plagiarism->Manage Plagiarism Plugins), I receive the following error:

Section error!
More information about this error

Debug info: 
Error code: sectionerror
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 6308 of /lib/adminlib.php: call to print_error()
line 27 of /plagiarism/turnitin/settings.php: call to admin_externalpage_setup()

**Comment by jmcgettrick** [comment]
Hi, we've never seen this reported before. I've taken a look at the admin_externalpage_setup() function in adminlib.php and it seems like Moodle is having trouble with the path but I can't reproduce your error.

We have heard isolated incidents of users having to purge their caches before the plagiarism plugin will work. It may not be installed correctly so this may also work in this case.

**Comment by daparker26** [comment]
Yes, there must have been something that went wrong during installation. After re-installing, the admin page is included in the tree and the settings page can be accessed without error. Thanks for your time!

**Comment by jmcgettrick** [comment]
No problem! @mhughes2k mentioned in a previous issue that this could be caused by the way we save the config settings - https://github.com/jmcgettrick/MoodleDirectV2/issues/108 

We'll get this looked at.
