### ISSUE TITLE
Seperate turnitin components into their own repos

### ISSUE THREAD

**Issue by hitteshahuja** [jmcgettrick/MoodleDirectV2#297]
Hi John,
Is it possible for you to seperate the different plugins in their own repositories just like you did for blocks_turnitin 2 days ago. It would be much simpler for consumers like us to pull the different repos rather than moving them around in their respective folders ( mod, plagiarism,blocks) after every fetch/pull.

Regards,
Hittesh

**Comment by jmcgettrick** [comment]
Hi Hittesh, we'll be doing this fairly soon. We did this with the block first as a trial run to see if it caused any issues and hasn't as yet so we'll get the other two planned in.
I'll close this particular issue as it's mentioned further down.
Thanks 
John
