### ISSUE TITLE
Database indexing issue

### ISSUE THREAD

**Issue by NeillM** [jmcgettrick/MoodleDirectV2#298]
The turnitintooltwo_submissions table could really do with an index on the submission_objectid column.

We have added it on our Moodle after we found that queries to that table were taking up a huge amount of our database time with full table scans.

![image](https://cloud.githubusercontent.com/assets/1038050/6623245/aa4f974a-c8d9-11e4-8ab5-b65f52fd3e3e.png)

The image shows the top 5 most time consuming database operations both before and after the index was added. The turnitintooltwo_submission select queries are in purple.

**Comment by jmcgettrick** [comment]
Hi Neill, we'll get this added for one of our upcoming releases.

**Comment by jmcgettrick** [comment]
Released in 2015040101.
