### ISSUE TITLE
Changing Turnitin Account raises error

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#30]
So each year we've segregated our Turnitin Submissions by creating a new sub account.

This year we're also merging from using Direct V1 & Dan Marsden's plugin to using _only_ Direct V2.

Our testing of this has led us to an interesting issue.

We have mod_assign activities in classes using the DM plugin. When we install the Direct V2 plagiarism plugin _over the top_ (which we have to do since they have the same name) and change the sub account ID in the settings, we see new classes being created in Turnitin _but not new assignments_.

This appears fine at first, I was expecting that a student submission to maybe trigger creation. However if a student then submits a piece of work into one of these assignments the cron event handler throws an exception:

```
++ Handler function of component plagiarism_turnitin: s:26:"event_assessable_submitted"; threw exception :turnitintooltwo/There was an error trying to edit the assignment in Turnitin<br/><br/>Fault Code: unknownobject | File: /moodle/web/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 108 | Message: Assignment LineItem not found. | Code: 0
* line 489 of /mod/turnitintooltwo/lib.php: call to print_error()
* line 127 of /mod/turnitintooltwo/turnitintooltwo_comms.class.php: call to turnitintooltwo_print_error()
* line 791 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to turnitintooltwo_comms->handle_exceptions()
* line 979 of /plagiarism/turnitin/lib.php: call to turnitintooltwo_assignment->edit_tii_assignment()
* line 1260 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->sync_tii_assignment()
* line 1770 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->event_handler()
* line ? of unknownfile: call to event_assessable_submitted()
* line 299 of /lib/eventslib.php: call to call_user_func()
* line 343 of /lib/eventslib.php: call to events_dispatch()
* line 450 of /lib/eventslib.php: call to events_process_queued_handler()
* line 340 of /lib/cronlib.php: call to events_cron()
* line 61 of /admin/cli/cron.php: call to cron_run()
 ++
* line 366 of /lib/eventslib.php: call to debugging()
* line 450 of /lib/eventslib.php: call to events_process_queued_handler()
* line 340 of /lib/cronlib.php: call to events_cron()
* line 61 of /admin/cli/cron.php: call to cron_run()
```

I'm going to see what happens if I turn the turnitin check off and then back on again...but this is quite problematic if we have to do this for every mod_assign activity that was using the previous DM Turnitin Plagarism Plugin.

**Comment by jasovik** [comment]
Does anybody know what it means when we see "Assignment Line Item Not Found".
We're using Managebac LTI integration and there's a yellow exclamation point and that message when I hover over it.
