### ISSUE TITLE
Config locking for all module / plagarism settings

### ISSUE THREAD

**Issue by brendanheywood** [jmcgettrick/MoodleDirectV2#305]
The normal assignment module can not only specify the defaults at the site level but also marked them as locked:

![image](https://cloud.githubusercontent.com/assets/187449/6666102/15ab016a-cc35-11e4-9566-6e1ca613e5e0.png)

I've implemented something similar to this for TII, if there is interest I'll clean it up to go into core.

**Comment by jmcgettrick** [comment]
Released in 2015040101.
