### ISSUE TITLE
File type restrictions

### ISSUE THREAD

**Issue by brendanheywood** [jmcgettrick/MoodleDirectV2#306]
TII only processes around a dozen file types / extension, in some cases it doesn't make sense to upload them to TII at all, and for big files it's pretty wasteful. eg an assignment where you upload a heavy binary like a photoshop file, and then a text doc along side it. 

* [ ] new module / plagarism / site default settings: Only upload files that can be checked [Yes | No]

I'm about to embark on implementing this in the next couple days so open to guidance / input

**Comment by jmcgettrick** [comment]
Hi Brendan, you can specify whether you wish to "Allow submission of any file type" in the plugin settings for each module. If that is set to "No" it won't interfere with the submission to the Moodle module, it just means that Turnitin will reject the submission if it isn't one of the accepted file types.

**Comment by brendanheywood** [comment]
I'm confused by the "Allow submission of any file type" it just doesn't seem to do anything and I can't find code at least on the moodle side that does anything with it. I see two scenarios:

1) above, where there are files you want submitted into moodle (eg a normal assignment) but you only want the files that can be processed by TII to be uploaded to TII. To accomplish this I'd want this new setting which just filters the list of files by extension before pushing it up. This would apply to anywhere the plagiarism plugin would be in use.

2) Another scenario specific to the TII2 module, if "Allow submission of any file type" is set to No, then instead the moodle file picker should be given the list of extensions so you can't even upload it to moodle. There is no point in pushing up a 5 meg file over ADSL into moodle, and then waiting for that to get pushed to TII and only then getting an error saying it was rejected, it's too late in the process. If you didn't want to override the meaning of that setting then it could be a new setting, or a conditional checkbox next to it.

As a side note, if I do set "Allow submission of any file type" to No and then upload something random like a heavy flash file, I get an uncaught exception error. This isn't ideal at all:

```
turnitintooltwo/There was an error trying to create the submission in Turnitin

Fault Code: failure | File: [dirroot]/mod/turnitintooltwo/sdk/lti.class.php | Line: 466 | Message: Your submission must contain 100 characters or more. | Code: 0
```

**Comment by jmcgettrick** [comment]
It isn't really used on the moodle side in the plagiarism plugin as we don't have a way of restricting files that are uploaded to the assignment. It is set on the Turnitin side and will reject files that an originality report definitely can not be generated for.

1) As an addition to what is currently in the plugin, we could filter by extension if necessary before sending to Turnitin but that file would still exist in the Moodle submission.

2) Currently we don't have the ability to edit the filepicker in Moodle, but I would imagine a change could be made to Moodle's Plagiarism API so that this was possible.

**Comment by brendanheywood** [comment]
> 1) As an addition to what is currently in the plugin, we could filter by extension if necessary before sending to Turnitin but that file would still exist in the Moodle submission.

Yup this is exactly what I had in mind and what I'll be doing. The files are still in moodle to be marked etc, but they are just not relevant to TII (ie because they are pictures or binaries etc)

> 2) Currently we don't have the ability to edit the filepicker in Moodle, but I would imagine a change could be made to Moodle's Plagiarism API so that this was possible.

This is a core API and is trivial, see 'accepted_types':

https://docs.moodle.org/dev/Using_the_File_API_in_Moodle_forms#Using_the_filepicker_element

**Comment by jmcgettrick** [comment]
We do that in the Turnitin Assignment type but as far as I know we can't override the filepicker that is created by Moodle from the plagiarism plugin.

**Comment by brendanheywood** [comment]
Re 1) I've thinking instead of simple Yes | No, I'd make it:

Which files will be uploaded to TII?
* All submitted files
* Only files which can be displayed or processed in TII
* Only files which can be processed by TII

I've got a reasonable idea about which extensions are processed based on this page:

http://turnitin.com/en_us/training/instructor-training/submitting-papers

But it is a little vague and mentions document types rather than extensions. If there a more firm and complete list of exact file extensions somewhere I can use? ie is .pptx powerpoint good? .htm vs .html? .ps vs .eps?

> We do that in the Turnitin Assignment type

https://github.com/jmcgettrick/MoodleDirectV2/blob/master/mod/turnitintooltwo/view.php#L100

Yes but it's not set to anything meaningful, just '*' when it could be optionally set to the list of extensions above.

**Comment by jmcgettrick** [comment]
It was removed last year when we introduced accepting all file types. It used to read: 
'accepted_types' => array('.doc', '.docx', '.rtf', '.txt', '.pdf', '.htm', '.html', '.odt', '.eps', '.ps', '.wpd', '.hwp', '.ppt', '.pptx', '.ppsx', '.pps')

**Comment by brendanheywood** [comment]
Awesome. Is there also a definitive list of extensions which can be
displayed but not processed?

Sent from my iPhone

On 17/03/2015, at 1:56 AM, John McGettrick <notifications@github.com> wrote:

It was removed last year when we introduced accepting all file types. It
used to read:
'accepted_types' => array('.doc', '.docx', '.rtf', '.txt', '.pdf', '.htm',
'.html', '.odt', '.eps', '.ps', '.wpd', '.hwp', '.ppt', '.pptx', '.ppsx',
'.pps')

—
Reply to this email directly or view it on GitHub
<https://github.com/jmcgettrick/MoodleDirectV2/issues/306#issuecomment-81714647>
.

**Comment by jmcgettrick** [comment]
Most files should be displayable via grademark but only as images. Only those which are capable of producing an Originality Report will be able to be displayed in the Originality Report section of the Document Viewer.

**Comment by brendanheywood** [comment]
I was thinking this would be a new option but on reflection this probably needs to be a third option for the "Allow submission of any file type" setting:

![image](https://cloud.githubusercontent.com/assets/187449/6704275/6570c958-cd9a-11e4-9088-2aa37217d222.png)

Can I get some feedback on this please?

**Comment by jmcgettrick** [comment]
Are option 1 and 3 not the same? I understand them to mean only accepting files that Turnitin will accept and ignoring everything else, is that correct?

**Comment by brendanheywood** [comment]
Sorry for the delay.

No - it's subtly different and why I want some feedback to make it clear. In scenario 1 any file can be uploaded into moodle, and they will all be pushed to TII but TII will barf on invalid files.

In the 3rd option the files are uploaded to moodle, but only valid ones are pushed to TII, so TII will never show an invalid type message. This is exactly what CQU want as they want an assignment to accept say a large binary and a text document side by side, but they do not want the binary sent to TII as it can't be process for originality, and it's just a waste of bandwidth and time to upload it (and they mark directly in moodle not using grademark for these assignments).

How about:
* Files must be an accepted type
* Any file will be available for download and GradeMark
* Any file submitted but only accepted types available for download and GradeMark

Or should we just make this a new independent option?

**Comment by jmcgettrick** [comment]
The "Accept any file type" is a boolean option in the API and the plagiarism_allow_non_or_submissions setting for each module is stored as 0/1 in the database so as long as we stick to that I don't see too much of a problem. 

For option 3 though you would have to filter non-accepted file types out on the Moodle side. If the assignment is set to accept all file types and Turnitin gets a file which is not one of it's readable file types, it will still image the file so it can be graded in GradeMark, there will just be no Originality Report.
