### ISSUE TITLE
Use moodle api to detect which modules can use plagiarism plugin

### ISSUE THREAD

**Issue by brendanheywood** [jmcgettrick/MoodleDirectV2#307]
ie instead of hard coded list of modules make it flexible and future proof:

```
$supported_mods = array('assign', 'forum', 'workshop');
```
vs
```
$mods = core_component::get_plugin_list('mod');
foreach ($mods as $mod => $moddir) {
    if (plugin_supports('mod', $mod, FEATURE_PLAGIARISM)) {
```

**Comment by mhughes2k** [comment]
There's the problem in that in that the TII has to know how to handle the data that comes from a given plugin, so it is legitimate that it doesn't support all plugins that indicate that *they* support the plagiarism API.

We've raised some concerns about the Plagiarism API and how this information is passed between the API and plugins that implement it, as we feel at the moment its a complete free-for-all with no properly defined interface (i.e. the is just a "bucket" (array) of data passed to the Plagiarism API, that a plugin has to work out what it represents)

**Comment by jmcgettrick** [comment]
As Michael says, the modules that are currently supported work in different ways so we have to adapt the plugin to fit. You'll see it a lot in the code that there are occasions where we do something differently path depending on what $cm->modname is.

So, at the minute it's not really feasible for us to say the plugin would definitely support a module that supports the Plagiarism API as we'd need to check it first.

**Comment by brendanheywood** [comment]
Yeah I totally agree that the api can be improved, and it seems to me that there is a big overlap here with #123, it looks like the majority of the $cm->modname forks are all around grading and not exactly plagiarism, and if it was moved to an advanced grading method a lot of these forks could disappear.
