### ISSUE TITLE
Allow Grademark Settings in plagiarism/turnitin

### ISSUE THREAD

**Issue by JeryH** [jmcgettrick/MoodleDirectV2#321]
We could really do with the ability to control the use of grademark independently in the two plugins:

> turnitintooltwo (we want to enable grademark)
> plagiarism/turnitin (we want to disable grademark)

This is because when using mod assign we always want grading and feedback to be done in Moodle.
As it stands, because we allow use of grademark in turnitintooltwo it is also available in mod assign.

Some staff are then clicking the big blue edit icon in gradebook (leading to grademark) as opposed to the tiny grey one (leading to Moodles internal grading page).

Having an admin setting for plagiarism/turnitin that allowed us to set this would be a big help.

**Comment by jmcgettrick** [comment]
Hi Jery, this is something that has been requested previously and we will look at implementing in the long term. I've dug out the previous request here: https://github.com/jmcgettrick/MoodleDirectV2/issues/135
