### ISSUE TITLE
New event classes in mod/turnitintooltwo have unnecessary methods defined.

### ISSUE THREAD

**Issue by sam-moodle** [jmcgettrick/MoodleDirectV2#324]
The new event classes all have get_legacy_eventname() defined, but return what looks to be filler text rather than the name of a legacy event (see https://github.com/jmcgettrick/MoodleDirectV2/blob/master/mod/turnitintooltwo/classes/event/add_submission.php#L37 for example). This will cause the events API to check for registered event handlers each time the new events are triggered.

It looks like there aren't legacy events that these are replacing in which case both get_legacy_eventname() and get_legacy_eventdata() can be removed.

**Comment by dulldave** [comment]
Hi @sam-moodle - Thanks for raising this, you're definitely right. We've now removed the pointless get_legacy_* methods from the event classes. You'll see this updated in the next version.
