### ISSUE TITLE
Checking in get_links() in wrong order (PP)

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/MoodleDirectV2#332]
The get_links() method in the plagiarism plugin is checking whether Turnitin is enabled for the module / module type and bailing out if it isn't, but this is done *after* the expensive test_turnitin_connection() call.

test_turnitin_connection() should only be called if Turnitin is in use for the mod instance.

**Comment by micaherne** [comment]
(This is on the develop branch)

**Comment by jmcgettrick** [comment]
I've moved the test connection in the develop branch. Regarding https://github.com/jmcgettrick/MoodleDirectV2/issues/335, we need to discuss internally what to do about this as we have been asked in the past to include a test connection.

I'll come back to you in that thread.

**Comment by micaherne** [comment]
Thanks, John!

**Comment by mhughes2k** [comment]
John, I think the point of this was that there isn't a need to check if Turnitin is up if it's *not* being used...rather than *not* testing if turnitin is up.
