### ISSUE TITLE
Notice during Moodle cli upgrade

### ISSUE THREAD

**Issue by NeillM** [jmcgettrick/MoodleDirectV2#345]
Only a minor thing, running a Moodle upgrade via the cli upgrade script (admin/cli/upgrade.php) generated the following PHP notice:

PHP Notice:  Undefined property: stdClass::$repositoryoption in /var/www/html/upgrade/mod/turnitintooltwo/settings.php on line 287

The upgrade was from Turnitin v12 to v13

**Comment by jmcgettrick** [comment]
This has been fixed by https://github.com/jmcgettrick/MoodleDirectV2/pull/284 and will be out in the next release
