### ISSUE TITLE
Headers and footers are rendered (and then hidden) in modal forms

### ISSUE THREAD

**Issue by barrysspace** [jmcgettrick/MoodleDirectV2#355]
in mod/turnitintooltwo/jquery/turnitintooltwo.js and turnitintooltwo_extra.js we have code like this:

    if ($("#view_context").html() == "box" || $("#view_context").html() == "box_solid") {
        // hide navbar, header, footer, etc
    }

This means that the elements are first rendered and then hidden via this code which changes the styling of the elements to display: none.  It would be more efficient to set a page layout like 'popup' or 'embedded' which would have prevented the elements from being rendered in the 1st place

**Comment by jmcgettrick** [comment]
Hi Barry, we've just changed this is in the release that went out a couple of weeks ago.
Thanks
John
