### ISSUE TITLE
Turnitin DV fails to load in Safari

### ISSUE THREAD

**Issue by alexumn** [jmcgettrick/MoodleDirectV2#356]
In Safari 8.0.4, when clicking the OR score or GradeMark icon in a Moodle PP activity, the Turnitin Document Viewer window opens but the content does not load completely. Instead, only the "Loading Document Viewer..." text appears, as seen below:

![screen shot 2015-04-14 at 12 00 46 am](https://cloud.githubusercontent.com/assets/8451469/7130632/752bf210-e239-11e4-8a57-c9210b1ec830.png)

This occurs in Turnitin Direct v2 2014012413 and 2015040101 on Moodle 2.8.5+ (Build: 20150326). We have not yet tested in Moodle 2.6 or 2.7.

**Comment by jmcgettrick** [comment]
Hi @alexumn, we had this issue raised last year and fixed it so I'm not sure why it doesn't work now. We'll get it fixed.

**Comment by jmcgettrick** [comment]
Hi @alexumn, this has been fixed and released in 2015040104.
