### ISSUE TITLE
PP fails to load grading page if turnitin error occurs

### ISSUE THREAD

**Issue by danmarsden** [jmcgettrick/MoodleDirectV2#364]
Part of this could be due to a copy of a production site being used for testing an upgrade.

Viewing the grading page of an assignment with PP enabled gives this fatal error:
/mod/assign/view.php?id=40636&action=grading
------------
turnitintooltwo/There was an error trying to find the user in Turnitin

File: [dirroot]/mod/turnitintooltwo/sdk/soap.class.php | Line: 257 | Message: SOAP-ERROR: Parsing WSDL: Couldn't load from '[dirroot]/mod/turnitintooltwo/sdk/wsdl/lis-person.wsdl' : failed to load external entity "[dirroot]/mod/turnitintooltwo/sdk/wsdl/lis-person.wsdl" | Code: 0

----------
preventing the grading page within Moodle from being displayed - it's probably fine to show the error but it should be a warning and still allow the grading page to be viewed.

**Comment by jmcgettrick** [comment]
Does this happen for one specific user or everyone?

**Comment by jmcgettrick** [comment]
Hi @danmarsden, is this still happening? Please reopen if it is.
