### ISSUE TITLE
Files removed from PP submission after grading are included in average grade calculation

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#376]
If a student is able to edit their submission after being given a grade, and they upload new files after deleting the originals, the PP calculates an average grade between all the files (even though the originals are now no longer part of the submission).

Fixed in https://github.com/lucisgit/MoodleDirectV2/commit/c425c9d490532928ee59166578484f35f68dbde3.

**Comment by tonyjbutler** [comment]
Actually my fix only works if there is only one file remaining in the submission. If there are several (plus one or more that have been graded and then removed from the submission) an average grade will still be  calculated, and it will be incorrect.

**Comment by jmcgettrick** [comment]
Hi @tonyjbutler, this has been included and released in 2015040104.
