### ISSUE TITLE
Notices on My home page

### ISSUE THREAD

**Issue by NeillM** [jmcgettrick/MoodleDirectV2#385]
For some users we get the following notices generated on the my home page:

Notice: Undefined variable: submissioncount in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1262

Notice: Undefined variable: submissioncount in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1263

Notice: Undefined offset: 3903 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1262

Notice: Undefined offset: 3903 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1263

Notice: Undefined offset: 1875 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1262

Notice: Undefined offset: 1875 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1263

Notice: Undefined offset: 3991 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1262

Notice: Undefined offset: 3991 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1263

Notice: Undefined offset: 3992 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1262

Notice: Undefined offset: 3992 in /var/www/html/upgrade/mod/turnitintooltwo/lib.php on line 1263

**Comment by NeillM** [comment]
Looking at the code and our database it seems to be happening to graders when a part has no submissions.

**Comment by jmcgettrick** [comment]
Yes, this has been fixed, it just required an array to be initialised. The commit is currently in the develop branch at https://github.com/jmcgettrick/MoodleDirectV2/commit/fd866539d779834a426fe58f5dac38109e53ed82

**Comment by NeillM** [comment]
Thanks

**Comment by jmcgettrick** [comment]
Hi @NeillM, this has been fixed and released in 2015040104.
