### ISSUE TITLE
Enrollment/Calendar 

### ISSUE THREAD

**Issue by Niki24** [jmcgettrick/MoodleDirectV2#389]
Hi. We use Moodle as our primary LMS and utilize the Turnitin plugin. Since
upgrading to the latest version (2015040102), we have encountered an issue with
enrollment. When attempting to cross-list courses, and a course has
a Turnitin assignment, we receive the following error:

"moodle_database::update_record_raw()id field must be specified."
 
![capture](https://cloud.githubusercontent.com/assets/3390307/7441758/bd80a0b8-f0c3-11e4-98e8-624aa6aaf674.PNG)

On the backend this error is: 

"PHP Notice: Trying to get property of non-object in
/var/www/html/moodle/mod/turnitintooltwo/lib.php on line 168"

It appears that it's not passing the instance id to the parent course. 

We would appreciate your assistance in aiding this. Thank you for
your time. 

![capture1](https://cloud.githubusercontent.com/assets/3390307/7441773/36e87c14-f0c4-11e4-92dc-d1e6ac13a5dd.PNG)

**Comment by jmcgettrick** [comment]
Hi, can you give us steps to reproduce this please?

**Comment by Niki24** [comment]
Hi. Thank you for your response. 

1. Navigate to your course. 
2. Under course administration, click on the users' arrow, click on enrolment methods
3. Under Add Method there will be a drop down, click on course meta link
4. Select the course you would like to cross-list (The course you are selecting will need to have a turnitin assignment). Click Add Method
5. "moodle_database::update_record_raw()id field must be specified" will display. 

I turned on turnitin debugging and this is the error I receive

![2015_05_04_16_42_12_error](https://cloud.githubusercontent.com/assets/3390307/7472587/10f35cbe-f302-11e4-9c70-50c4747c7197.png)

I do not receive the error if I comment out :
$updatedevent->id = $event->id(located /var/www/html/moodledev/mod/turnitintooltwo/lib.php) , however, it creates a problem with quick update on the course home page and calendar events.

**Comment by jmcgettrick** [comment]
I'm closing this as the case has come through Turnitin support. For the benefit of anyone who has a similar error though, you don't appear to have Moodle Direct correctly configured or it may have expired. Your account administrator needs to login to the Turnitin website and go to the integrations dashboard to configure Moodle Direct.

**Comment by Niki24** [comment]
If anyone else is having this issue, the developer revised their code:
located /var/www/html/moodlefolder/mod/turnitintooltwo/lib.php

    $parts = $DB->get_records_select("turnitintooltwo_parts", " turnitintooltwoid = ? ",
                                        array($turnitintooltwo->id), 'id ASC');
    foreach ($parts as $part) {
        if ($event = $DB->get_record_select("event",
                                        " modulename = 'turnitintooltwo' AND instance = ? AND courseid = ? AND name LIKE ? ",
                                        array($turnitintooltwo->id, $turnitintooltwo->course, '% - '.$part->partname))) {
        $updatedevent = new stdClass();
        $updatedevent->id = $event->id;
        $updatedevent->userid = $USER->id;
        $updatedevent->name = $turnitintooltwo->name." - ".$part->partname;

        $DB->update_record('event', $updatedevent);

        } 
    }
}

**Comment by jmcgettrick** [comment]
Apologies, I should've updated this issue but it slipped though the net. The commit for the fix is in the develop branch at the moment https://github.com/jmcgettrick/MoodleDirectV2/commit/de55851d59571c72bfb8e7842c58f1495a580708
