### ISSUE TITLE
curl timeout values too high.

### ISSUE THREAD

**Issue by danmarsden** [jmcgettrick/MoodleDirectV2#390]
When the Turnitin API is performing slowly and the site has a large number of assignment submissions the web server uses up a lot of clients quite quickly which can result in the Moodle site performing quite badly due to the large number of open requests.

The CURLOPT_CONNECTTIMEOUT is hard coded to 30seconds which is quite a high value to use for the connection and the CURLOPT_TIMEOUT is set to 120 and 600 in different places.

At the very least the CONNECTTIMEOUT value should be much lower (5 seconds would be a much better value) and does the TIMEOUT value really need to be that high?

We have a client that experienced significant outages of their Moodle site on the 23rd April that seemed to be attributed to the poor performance of the Turnitin API and due to those timeout values they ended up with a significant number of apache requests being held up and caused their Moodle server to be unavailable to users.

**Comment by jmcgettrick** [comment]
This isn't going to be something we can change easily. We're aware the plugin can be server intensive but in some instances it is dealing with a large quanitity of data, we actually have an issue currently where the CURLOPT_TIMEOUT value is too low and causing issues for one institution.

We could investigate this though to see whether it's feasible to change for requests where we expect relatively small exchanges of data.
