### ISSUE TITLE
Warning about resubmissions displays even after due date.

### ISSUE THREAD

**Issue by ianmcn** [jmcgettrick/MoodleDirectV2#391]
We're currently on 2015040102 but have had this issue on previous versions too. When clicking to go to Grademark, it gives the pre-due date warning that grades could be overwritten if resubmission occurs, but it gives this warning even after the due date. See screenshot taken today showing due date from last month.

![hrm_assignment_link_feb-june_2015_-_in_maintenance_mode](https://cloud.githubusercontent.com/assets/2265103/7479460/d1ab6c38-f372-11e4-93c1-92280665b758.jpg)

**Comment by jmcgettrick** [comment]
This has been fixed and released in 2015040106.
