### ISSUE TITLE
Change to output from print_overview function as used by block_course_overview

### ISSUE THREAD

**Issue by EdinburghNapier** [jmcgettrick/MoodleDirectV2#394]
After upgrade to 2015040102, information displayed to graders from the turnitintooltwo_print_overview function no longer includes zeros when there are no submissions or no graded submissions.

An example would be:

![image](https://cloud.githubusercontent.com/assets/3405195/7497802/b2aa9924-f414-11e4-8221-b1d7c8b9f64e.png)

Previously the last line for these assignments would have been 0/61 Student Submission, 0 Submissions Graded

**Comment by EdinburghNapier** [comment]
Just realised this may be the same issue as #385, apologies if so.

**Comment by EdinburghNapier** [comment]
Commit fd86653 fixes this. Thanks.

**Comment by jmcgettrick** [comment]
No problem!
