### ISSUE TITLE
Class Expiry Dates

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#401]
We've had a few classes that are coming up with expiry dates of 2/May 2015 and 9 May 2015, and we're trying to work out how they've become expired. 

Is the expiry date fixed at creation or is there something in the TII plugin that will roll it forward?

We've been able to unexpire the classes directly in TII by editing the settings (this prompts us to enter a subject and level, before it will let us save, which is a bit annoying), but ideally we'd like to keep the classes unexpired just now. 

If there is a setting in the class that updates this in TII it would be good to know.

**Comment by jmcgettrick** [comment]
The class expiry date is set to 6 months ahead of the latest date on an assignment, this should then be pushed forward as and when assignments are created/edited.

There's a class migration tool in the Site Administration .... Turnitin Assignment 2 area, that gives you the ability to search all classes on your Turnitin account and also allows editing of the class end date if you need to.

**Comment by mhughes2k** [comment]
I've looked in to this a bit more, and it would appear that all of the assignments in this class were created in our Moodle site on the 18th September.

6 months later would make the initial expiry March 18. This is unfortunately a 2 semester long class, of if the lecturer has been really organised and added their assignments at the start of term (which they appear to have been), the class (on TII) would expire before the end of the 2nd semester

This year our teaching ran 26 September 2014 to 5th June 2015, which is *8 months and 9 days*.

In addition we get some staff starting to setup classes in June, so the time until a class expires at the end of the next academic year could be closer to 12 months!

Would there be any prospect of making the initial amount of time until expiry configurable in the plugin?

**Comment by jmcgettrick** [comment]
When an assignment is edited, if the due date or post date is set to be past the current class end date, then the class end date is modified. E.g. if the due date of an assingment is on 18/06 and the class end date on 18/10. If you then edit the assignment due date to be 22/10 Turnitin will alter the class end date to 22/10.

You can currently edit the class end dates in the Course Migration Tool but if an issue arises from the current behaviour we'll look at adding in functionality to change the end date automatically.
