### ISSUE TITLE
Turnitin processing files that aren't student submissions

### ISSUE THREAD

**Issue by hitteshahuja** [jmcgettrick/MoodleDirectV2#407]
Hi John,
Our team at Bath has raised this on the turnitin help desk and this has been confirmed as a bug by Turnitin .Dont want to duplicate the issue so will just redirect you to the issue at Turnitin Helpdesk. The ticket number is #00419795 - 1301 The University of Bath - CN-010699.

It would be great if you could look at it at your earliest convenience.

Thanks,
Hittesh

**Comment by jmcgettrick** [comment]
Hi Hittesh,
We will get that fixed as soon as we can. It's in our plan to work on in the next week or so.
Cheers
John

**Comment by ianmcn** [comment]
Hi Hittesh

Any chance you could describe the issue a bit more here? It sounds like it
might be something similar to what we're experiencing that we've struggled
to get to the bottom of.

Thanks

Ian

**Comment by jmcgettrick** [comment]
Hi Ian, it's that additional files added by the instructor to a Moodle assignment are being submitted to Turnitin. 
It's fixed by https://github.com/jmcgettrick/MoodleDirectV2/pull/408 but hasn't been merged in yet.

**Comment by hitteshahuja** [comment]
Hi John
Many thanks for your swift reply and commit. My colleague has tested and it works as expected ! Waiting for the branch to be merged into master . 

Thanks !

**Comment by jmcgettrick** [comment]
This has been released in 2015040105.
