### ISSUE TITLE
Restore without users failing

### ISSUE THREAD

**Issue by daparker26** [jmcgettrick/MoodleDirectV2#410]
I've recently ran into a problem when I backup and restore courses from one Moodle installation to another without including user data. It seems the Turnitin plugin ignores that the course is being restored without user data and attempts to enroll the students in the assignment on restore. Of course, since there are no students in the newly restored class, the Turnitin assignment throws an error and fails to restore.

I see that the after_restore() function in restore_turnitintooltwo_activity_task.class.php is supposed to create a new course if no user data was restored, so not sure what is throwing the error. In my case, the course was not reset before backed up and it was restored as an administrator into a course with no users at all (not even instructors).

To reproduce:
1) Create a course with a Turnitin assignment
2) Enroll users (and ensure they are enrolled in the Turnitin assignment)
3) Backup the course without user data
4) Attempt course restore on another site (or maybe even the same site. I haven't tested)
5) Turnitin throws an error

**Comment by jmcgettrick** [comment]
Hi @daparker26, we've been trying to reproduce this error but aren't having any success. Can you give us a screenshot or log entry of the error you are getting?

Also, which Moodle versions are you using for backing up and restoring?

**Comment by daparker26** [comment]
Hi @jmcgettrick, thanks for responding. I was attempting to restore a course from one Moodle 2.6 install to another 2.6 install. Using Moodle Direct v2 version 2014012413 (old, I know).

Here are the debugging notes from Moodle:

Notice: Trying to get property of non-object in /var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php on line 78

Warning: Creating default object from empty value in /var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php on line 80

Notice: Undefined property: stdClass::$firstname in /var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php on line 83

Notice: Undefined property: stdClass::$lastname in /var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php on line 84

Notice: Undefined property: stdClass::$username in /var/www/html/mod/turnitintooltwo/turnitintooltwo_user.class.php on line 86
turnitintooltwo/Turnitin user creation failed

Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 39 | Message: first_name - This field is required last_name - This field is required email - This field is required | Code: 0

More information about this error

Debug info: 
Error code: Turnitin user creation failed<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 39 | Message: first_name - This field is required 
last_name - This field is required 
email - This field is required 
| Code: 0
$a contents: Turnitin user creation failed<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/usersoap.class.php | Line: 39 | Message: first_name - This field is required 
last_name - This field is required 
email - This field is required 
| Code: 0
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 559 of /mod/turnitintooltwo/lib.php: call to print_error()
line 140 of /mod/turnitintooltwo/turnitintooltwo_comms.class.php: call to turnitintooltwo_print_error()
line 254 of /mod/turnitintooltwo/turnitintooltwo_user.class.php: call to turnitintooltwo_comms::handle_exceptions()
line 169 of /mod/turnitintooltwo/turnitintooltwo_user.class.php: call to turnitintooltwo_user->create_tii_user()
line 45 of /mod/turnitintooltwo/turnitintooltwo_user.class.php: call to turnitintooltwo_user->get_tii_user_id()
line 98 of /mod/turnitintooltwo/backup/moodle2/restore_turnitintooltwo_activity_task.class.php: call to turnitintooltwo_user->__construct()
line 111 of /backup/util/plan/restore_task.class.php: call to restore_turnitintooltwo_activity_task->after_restore()
line 193 of /backup/util/plan/restore_plan.class.php: call to restore_task->execute_after_restore()
line 115 of /backup/moodle2/restore_final_task.class.php: call to restore_plan->execute_after_restore()
line 506 of /backup/moodle2/restore_stepslib.php: call to restore_final_task->launch_execute_after_restore()
line 34 of /backup/util/plan/restore_execution_step.class.php: call to restore_execute_after_restore->define_execution()
line 181 of /backup/util/plan/base_task.class.php: call to restore_execution_step->execute()
line 177 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
line 167 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 333 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 184 of /backup/util/ui/restore_ui.class.php: call to restore_controller->execute_plan()
line 99 of /backup/restore.php: call to restore_ui->execute()

_____________________

And here are the API logs for the errors:

------------------------------------------------------------
2015-06-11 14:40:29 -0500 - INFO -->
------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <tns:imsx_syncResponseHeaderInfo xmlns:tns="http://www.imsglobal.org/services/lis/pms2p0/wsdl11/sync/imspms_v2p0">
      <tns:imsx_version>V1.0</tns:imsx_version>
      <tns:imsx_messageIdentifier>8DBE1E6E-1071-11E5-9618-99430838E813</tns:imsx_messageIdentifier>
      <tns:imsx_statusInfo>
        <tns:imsx_codeMajor>failure</tns:imsx_codeMajor>
        <tns:imsx_severity>error</tns:imsx_severity>
        <tns:imsx_messageRefIdentifier>c3fa8664-9f7b-434a-9bfa-2a8140c93452</tns:imsx_messageRefIdentifier>
        <tns:imsx_description>first_name - This field is required 
last_name - This field is required 
email - This field is required 
</tns:imsx_description>
        <tns:imsx_codeMinor>
          <tns:imsx_codeMinorField>
            <tns:imsx_codeMinorFieldName>TargetEndSystem</tns:imsx_codeMinorFieldName>
            <tns:imsx_codeMinorFieldValue>invaliddata</tns:imsx_codeMinorFieldValue>
          </tns:imsx_codeMinorField>
        </tns:imsx_codeMinor>
      </tns:imsx_statusInfo>
    </tns:imsx_syncResponseHeaderInfo>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <tns:createByProxyPersonResponse xmlns:tns="http://www.imsglobal.org/services/lis/pms2p0/wsdl11/sync/imspms_v2p0"/>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

------------------------------------------------------------

------------------------------------------------------------
2015-06-11 14:40:31 -0500 - INFO -->
------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <tns:imsx_syncResponseHeaderInfo xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0">
      <tns:imsx_version>V1.0</tns:imsx_version>
      <tns:imsx_messageIdentifier>8F287AB0-1071-11E5-A906-440245F2949E</tns:imsx_messageIdentifier>
      <tns:imsx_statusInfo>
        <tns:imsx_codeMajor>failure</tns:imsx_codeMajor>
        <tns:imsx_severity>error</tns:imsx_severity>
        <tns:imsx_messageRefIdentifier>587218e8-7af0-45ea-96b5-92d1003bf760</tns:imsx_messageRefIdentifier>
        <tns:imsx_description>user_role - User already enrolled on this Class CourseSection 
</tns:imsx_description>
        <tns:imsx_codeMinor>
          <tns:imsx_codeMinorField>
            <tns:imsx_codeMinorFieldName>TargetEndSystem</tns:imsx_codeMinorFieldName>
            <tns:imsx_codeMinorFieldValue>invaliddata</tns:imsx_codeMinorFieldValue>
          </tns:imsx_codeMinorField>
        </tns:imsx_codeMinor>
      </tns:imsx_statusInfo>
    </tns:imsx_syncResponseHeaderInfo>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <tns:createByProxyMembershipResponse xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0"/>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

------------------------------------------------------------

------------------------------------------------------------
2015-06-11 14:40:38 -0500 - INFO -->
------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <tns:imsx_syncResponseHeaderInfo xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0">
      <tns:imsx_version>V1.0</tns:imsx_version>
      <tns:imsx_messageIdentifier>93917C1E-1071-11E5-993A-E163E2C37434</tns:imsx_messageIdentifier>
      <tns:imsx_statusInfo>
        <tns:imsx_codeMajor>failure</tns:imsx_codeMajor>
        <tns:imsx_severity>error</tns:imsx_severity>
        <tns:imsx_messageRefIdentifier>d1ef3e4e-840e-443e-a4c9-7c6d842c2006</tns:imsx_messageRefIdentifier>
        <tns:imsx_description>user_role - User already enrolled on this Class CourseSection 
</tns:imsx_description>
        <tns:imsx_codeMinor>
          <tns:imsx_codeMinorField>
            <tns:imsx_codeMinorFieldName>TargetEndSystem</tns:imsx_codeMinorFieldName>
            <tns:imsx_codeMinorFieldValue>invaliddata</tns:imsx_codeMinorFieldValue>
          </tns:imsx_codeMinorField>
        </tns:imsx_codeMinor>
      </tns:imsx_statusInfo>
    </tns:imsx_syncResponseHeaderInfo>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <tns:createByProxyMembershipResponse xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0"/>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

------------------------------------------------------------

------------------------------------------------------------
2015-06-11 14:42:24 -0500 - INFO -->
------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <tns:imsx_syncResponseHeaderInfo xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0">
      <tns:imsx_version>V1.0</tns:imsx_version>
      <tns:imsx_messageIdentifier>D2C8B604-1071-11E5-8732-DE450838E813</tns:imsx_messageIdentifier>
      <tns:imsx_statusInfo>
        <tns:imsx_codeMajor>failure</tns:imsx_codeMajor>
        <tns:imsx_severity>error</tns:imsx_severity>
        <tns:imsx_messageRefIdentifier>30c14abc-abb4-47d2-8dd5-44b0ffb5f2ec</tns:imsx_messageRefIdentifier>
        <tns:imsx_description>user_role - User already enrolled on this Class CourseSection 
</tns:imsx_description>
        <tns:imsx_codeMinor>
          <tns:imsx_codeMinorField>
            <tns:imsx_codeMinorFieldName>TargetEndSystem</tns:imsx_codeMinorFieldName>
            <tns:imsx_codeMinorFieldValue>invaliddata</tns:imsx_codeMinorFieldValue>
          </tns:imsx_codeMinorField>
        </tns:imsx_codeMinor>
      </tns:imsx_statusInfo>
    </tns:imsx_syncResponseHeaderInfo>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <tns:createByProxyMembershipResponse xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0"/>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

------------------------------------------------------------

------------------------------------------------------------
2015-06-11 14:42:28 -0500 - INFO -->
------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <tns:imsx_syncResponseHeaderInfo xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0">
      <tns:imsx_version>V1.0</tns:imsx_version>
      <tns:imsx_messageIdentifier>D4D3E1DA-1071-11E5-B487-65B0FB0661C4</tns:imsx_messageIdentifier>
      <tns:imsx_statusInfo>
        <tns:imsx_codeMajor>failure</tns:imsx_codeMajor>
        <tns:imsx_severity>error</tns:imsx_severity>
        <tns:imsx_messageRefIdentifier>51334f61-d50d-4385-a93f-59db632eecf4</tns:imsx_messageRefIdentifier>
        <tns:imsx_description>user_role - User already enrolled on this Class CourseSection 
</tns:imsx_description>
        <tns:imsx_codeMinor>
          <tns:imsx_codeMinorField>
            <tns:imsx_codeMinorFieldName>TargetEndSystem</tns:imsx_codeMinorFieldName>
            <tns:imsx_codeMinorFieldValue>invaliddata</tns:imsx_codeMinorFieldValue>
          </tns:imsx_codeMinorField>
        </tns:imsx_codeMinor>
      </tns:imsx_statusInfo>
    </tns:imsx_syncResponseHeaderInfo>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <tns:createByProxyMembershipResponse xmlns:tns="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0"/>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

------------------------------------------------------------

Thank you for your help!

**Comment by jmcgettrick** [comment]
Hi @daparker26, thanks for the details. What I think is happening is that the course was created by a user id that doesn't exist in the new installation. The plugin is then trying to enrol create that user and enrol them on the class but as they are non existant, it's using empty details. 

In the stack trace:

line 169 of /mod/turnitintooltwo/turnitintooltwo_user.class.php: call to turnitintooltwo_user->create_tii_user()
line 45 of /mod/turnitintooltwo/turnitintooltwo_user.class.php: call to turnitintooltwo_user->get_tii_user_id()
line 98 of /mod/turnitintooltwo/backup/moodle2/restore_turnitintooltwo_activity_task.class.php: call to turnitintooltwo_user->__construct()

And the errors further up indicating that user creation failed. 

The best way that I can see around this is to replace all the mentions of $_SESSION['course_owner_id'] with the main site administrator. We'll get that done and out in our next release.

**Comment by daparker26** [comment]
Excellent. Thanks @jmcgettrick for looking into this.

**Comment by jmcgettrick** [comment]
That fix has now been released in 2015040106.
