### ISSUE TITLE
Message about unsigned columns on install

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/MoodleDirectV2#422]
When installing, I'm getting a message about unsigned values:

```
All unsigned numbers are converted to signed automatically during Moodle upgrade.

    line 607 of /lib/ddl/database_manager.php: call to debugging()
    line 110 of /mod/turnitintooltwo/db/upgrade.php: call to database_manager->change_field_unsigned()
    line 704 of /lib/upgradelib.php: call to xmldb_turnitintooltwo_upgrade()
    line 422 of /lib/upgradelib.php: call to upgrade_plugins_modules()
    line 1628 of /lib/upgradelib.php: call to upgrade_plugins()
    line 434 of /admin/index.php: call to upgrade_noncore()
```

I think this is because the turnitintooltwo plugin is still trying to use unsigned columns when these haven't been supported in Moodle for quite a few versions: https://tracker.moodle.org/browse/MDL-27982

(This is on the latest Moodle 2.8.6+ codebase)

**Comment by jmcgettrick** [comment]
Hi @micaherne, we changed one of the columns from unsigned to signed in the last release. To do that you've to call $dbman->change_field_unsigned($table, $field); which outputs a debugging message.

Most of the integer columns in the plugin are unsigned so we'll get those changed.

**Comment by jmcgettrick** [comment]
We've changed all the integer columns in the install.xml to now be signed for 2015040106.
