### ISSUE TITLE
Unable to hide Turnitin assignment in Moodle unit

### ISSUE THREAD

**Issue by angemmell** [jmcgettrick/MoodleDirectV2#426]
The Moodle settings "restrict access" setting does not hide the Turnitin assignment from students as they are able to by-pass the Moodle restrict access options by going directly to the Grades and clicking on the assignment link.

We recently had student who posted a direct link to the Turnitin assignment on Facebook and they were able to access the assignment even though the teacher had used restrict access to hide it on the unit page

At the moment it is only the post date that prevents students viewing feedback and grades.
We would like the Moodle settings"restrict access" to override the Turnitin plugin settings.when releasing an assignment to students

Anna

**Comment by jmcgettrick** [comment]
This has been fixed and released in 2015040106.
