### ISSUE TITLE
How to retrospectively show similarity scores after upgrade from v1 to v2?

### ISSUE THREAD

**Issue by hitteshahuja** [jmcgettrick/MoodleDirectV2#427]
Similarity scores received by API V1 ( using Dan Marsden's plagiarism plugin) are not shown when upgraded to Moodle Direct v2 ( Api v2) . Moving away from Dan Marsden's code to the new MoodleDirectv2 PP doesnt display the similarity score after you upgrade the plugin. For users who have not submitted anything using the new PP, it says "This file has not been submitted to Turnitin because the user has not accepted the Turnitin End User Licence Agreement. "

But these files have already achieved their similarity score in the old version.
Just wondering if this is an upgrade bug or some setting to bypass for existing submissions. It wont be an easy task telling every student that they need to potentially submit a new assignment before they (or teachers) could see their previously obtained similarity score. 

I see there is an turnitintooltwo_users table which has the user_agreement_accepted field , but I guess I cant mass populate that since it doesnt have the corresponding turnitin_uid with it(or can I ? )

**Comment by jmcgettrick** [comment]
The plugin checks whether a user has accepted the EULA previously using that field, if they haven't then the relevant message you've seen is shown. The problem you'll have is that none of your users will be in that table currently, the easiest way to achieve this is going to be to create a Turnitin Assignment in the same course and use the enrol all students link in the Turnitin Students tab.

**Comment by hitteshahuja** [comment]
But I would have to replicate that on 100's of courses across the site as I have noticed that the 'Turntin Students' tab once picks up enrolments from that course. Another way would be enroll all users in the system onto a single global course and then create a turnitin assignment for that course which wouldn't go down that well with academics and students alike. 
Also, we dont plan to use TT2 assignment activity at the moment. 
I tried doing this for a single course and here are my findings: 

1) Create a Turnitin 2 Assigment with default values. 
2) Use the Turnitin Users tab to add all students from that course.
3)turnitintooltwo_users  does show those users  with their relevant turnitin id. Still turnitin user agreement is set to 0. I manually edit the table to set it to 1 for them.
4) Run the cron. Check the PP assignment. Still no similarity score.
5)I login as a student and click on the PP assignment. I then see a message on the lines of ' submitted to turnitin' . 
6) Run the cron again.
7) Login as teacher and I see the similarity score for that student

Question : How can i possibly automate this for users so when we upgrade all these are already done for them so they don't have to edit every submission just to get similarity score for the old ones.

many thanks

Hittesh

**Comment by jmcgettrick** [comment]
Is there anything different between the file/user information that is passed to the get_links() function lib.php in comparison to what exists in the mdl_plagiarism_turnitin_files table? Files shouldn't re-submit if they are already present in the database.

**Comment by hitteshahuja** [comment]
I see that the contenthash matches the identifer in mdl_plagiarism_turnitin_files . Same goes for the userid and cm id. Although I see the similarity score for that file in mdl_plagiarism_turnitin_files table. I also see a status code of 51 besides it which is probably the reason its still not visible in gui.

**Comment by hitteshahuja** [comment]
Hi John,
Any progress with this ? We've also contacted Caroline Westgarth highlighting the same issue and are awaiting a response. We would like to go to tii direct v2 which is believe is what Caroline would very much like as well but we need to get rid of this road blocker first.
Many thanks,
Hittesh

**Comment by jmcgettrick** [comment]
Apologies for the delay in replying, the get_links function will only display submissions that have success as the status code. If it's not error or success (pending) then it will either show nothing or if the user has not accepted the EULA then it will show that.

I'll close this for now as Caroline is speaking to your institution directly.

**Comment by jmcgettrick** [comment]
I've modified the plugin slightly to account for previous submissions. This will be in the next release: https://github.com/jmcgettrick/MoodleDirectV2/pull/459
