### ISSUE TITLE
Grades being overwritten (multiple attempts) - PP

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/MoodleDirectV2#442]
We're seeing a pretty bad issue with the new version of the plagiarism plugin, v2015040105. Where a student is given multiple attempts for an assignment, any marks given in Grademark appear always to be stored against the initial submission, so Moodle grades are being wrongly overwritten.

To reproduce:

1. Create an assignment with "attempts reopened" setting set to "manually".
2. As a student, submit a file and wait until it is uploaded to TII
3. As staff, go in to the "view / grade all submissions" page, and click on the Grademark icon
4. Give the student a mark of 10, close GM and wait until the mark appears in Moodle
5. Click edit next to the student's submission and select "allow another attempt"
6. Repeat steps 2 & 3, but give the student a mark of 20, close GM and wait until the "view / grade" page refreshes itself

You will notice that the mark of 20 is not visible on the view / grade page at all, and if you log back in as the student, you'll see that the original attempt's grade of 10 has been overwritten with the new grade of 20, instead of this being against the second attempt, which will still show as "not graded".

**Comment by micaherne** [comment]
We're also seeing unpredictable (and changing) paper IDs in this scenario.
When the student initially uploads an attempt, and the Ajax upload happens, it's showing one paper ID, but after running the cron job, and viewing the view/grade page as staff, if the student refreshes the page, the displayed paper ID changes (I think to one of the ones from a previous attempt, which now appear to have been re-uploaded and have new paper IDs attached).

**Comment by micaherne** [comment]
Just to be clear, although this might not seem like a particularly major bug, I can't reasonably install this version of the plugin on our live systems as it's overwriting Moodle grades with spurious values.

**Comment by jmcgettrick** [comment]
This has been sorted and is now in the develop branch. We hope to get it out early next week.

**Comment by micaherne** [comment]
Thanks, John!
