### ISSUE TITLE
smtp settings checks too picky

### ISSUE THREAD

**Issue by NeillM** [jmcgettrick/MoodleDirectV2#453]
The following commit:

https://github.com/jmcgettrick/MoodleDirectV2/commit/c3d56fe5746a385466b891b0a7f86fd21a7843b5

Added checks to see if smtp was configured, however its checks are too strict. It requires that the following are set:

* smtphosts
* smtpuser
* smtppass

However a username and password are not always required for a valid smtp connection. This means in some environments the Turnitin plugin will refuse to send messages to users.

**Comment by jmcgettrick** [comment]
These constraints have been removed with v2015040109.
