### ISSUE TITLE
Display issue when accepting EULA

### ISSUE THREAD

**Issue by esslw** [jmcgettrick/MoodleDirectV2#461]
In Moodle 2.8, when a student accepts the EULA (using the plagiarism plugin), the following appears :

![funny display issue](https://cloud.githubusercontent.com/assets/13046792/8351102/acb22bce-1b22-11e5-9206-3d8ee7e49e1b.png)

(This is on a test server, so we have debugging turned on)

**Comment by jmcgettrick** [comment]
Hi, a string is missing from the english language pack. This had been in previously, but was updated to give different messages pre & post submission. It's not actually needed anymore so we'll get it removed.

**Comment by hitteshahuja** [comment]
Thanks John.Let me know when its done and I'll pull in the changes.

**Comment by jmcgettrick** [comment]
This has now been removed with v2015040109
