### ISSUE TITLE
No error reporting

### ISSUE THREAD

**Issue by esslw** [jmcgettrick/MoodleDirectV2#462]
Not sure if this is intended, however in our tests of the plagiarism plugin we have noticed that there is a lack of error reporting when something cannot be processed - as you might imagine, this will make troubleshooting issues tricky.

The following submission resulted in error 423 - this is not recorded anywhere however.  Teachers simply see a red cross showing that the file could not be processed, and the student sees the following screen:

![no error report](https://cloud.githubusercontent.com/assets/13046792/8351366/ac7f2fc4-1b24-11e5-860e-0d7a655a77b2.png)

Again, there is no indication of what the error is.

**Comment by jmcgettrick** [comment]
Is this because debugging is turned on and there is an error/notice being output within the javascript submission? The javscript then won't be able to grab the message it's intending to display in that instance.

**Comment by hitteshahuja** [comment]
Hi John,Debugging is turned off on that moodle instance. Would you point out where to look for messages. I dont see an XHR request or any other error msgs on the grading screen.
