### ISSUE TITLE
Problem with Direct v2 returning on due date

### ISSUE THREAD

**Issue by hitteshahuja** [jmcgettrick/MoodleDirectV2#465]
Another issue with plagiarism plugin.

Assignments setup to return orignality reports on due date does not seem to work.

To reproduce:
1. Add a new assignment with PP turned on 
2. Set it to return similarity score on due date
3. Submit assignment files as students
4. Run the cron to send the files to turnitin
5. On due date, say the next day, run the cron to fetch the similarity score. 

This , however does seem to work when you press the Refresh Button under Assignment Settings 

![image](https://cloud.githubusercontent.com/assets/2855029/8409110/169c9432-1e6d-11e5-8cbd-83872151a984.png)

Any reason why it wouldnt work with the cron function .

Many thanks,
Hittesh

**Comment by jmcgettrick** [comment]
Thanks Hittesh, we'll get this looked at.
