### ISSUE TITLE
GradeMark option: Use rubric belonging to other instructor

### ISSUE THREAD

**Issue by angemmell** [jmcgettrick/MoodleDirectV2#469]
We are currently testing (Moodle Direct v2, v2015040105) on our test site.

In the Turnitin assignment settings, under GradeMark options, it is currently defaulting to "use rubric defaulting to other instructor" in the attach a rubric to assignment drop down menu.

I have not been able to find any information about what this setting means, are you able to provide any more information. 

Regards
Anna

**Comment by jmcgettrick** [comment]
A user can currently only see rubrics belonging to themselves. If an assignment has more than 1 instructor and instructor2 attaches a rubric to an assignment, then instructor1 would see "Use rubric belonging to other instructor" in the rubric drop down.
