### ISSUE TITLE
Title limit characters

### ISSUE THREAD

**Issue by angemmell** [jmcgettrick/MoodleDirectV2#481]
We recently updated to Turnitin Moodle Direct v. v201504010

A lecturer received the following error message when making a copy of a previous unit including Turnitin assignments and title limit

![untitled](https://cloud.githubusercontent.com/assets/12619246/8664736/946bcd80-2a1e-11e5-8df0-852599318ef0.png)

I thought this issue had been fixed in Feb 2014, could you please provide more information about what may be causing this error.

Regards
Anna

**Comment by jmcgettrick** [comment]
What are you trying to name the assignment & parts? We do have validation that limits the lengths of the names of both the assignment and the parts to 40 characters each so when copying the assignment something might be getting added to the name?
