### ISSUE TITLE
Submissions deleted in Moodle PP don't get deleted in Turnitin

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#484]
If a student submits several drafts of a submission to a PP-enabled assignment, each file gets uploaded to Turnitin, and they all remain there even when the student deletes them in Moodle to upload the next draft or the final submission. If a teacher then attempts to grade the assignment in GradeMark without returning to Moodle between each student (e.g. by using the Turnitin iPad app or the navigation built into the GradeMark DV) they have no way of differentiating the final submission from the drafts.

Is it possible to cascade the deletion of previously submitted files from Moodle to Turnitin? Perhaps using a similar approach to the one used to exclude deleted files from the average grade calculation in https://github.com/jmcgettrick/MoodleDirectV2/commit/925533ccbbebd0c5b71ce15b283dd8d88686790a? The files would not need to be deleted outright, but could just be hidden from the teacher in GradeMark (perhaps with an option to view them if so desired).

Thanks,
Tony

**Comment by jmcgettrick** [comment]
This should be being done already when a user submits, we'll get it double checked though. When a submission is made, there is a function called clean_old_turnitin_submissions that removes files from Turnitin that are no longer part of a Moodle submission. The functionality was removed for a while but was then reinstated.

**Comment by jmcgettrick** [comment]
We double checked this in v2015040109 and submissions that are no longer part of an assignment are removed when submitting a new file.
