### ISSUE TITLE
Attaching rubrics to parts of a Turnitin assignment

### ISSUE THREAD

**Issue by angemmell** [jmcgettrick/MoodleDirectV2#485]
I had a query from an academic who had 2 parts in a Turnitin assignment and wanted to attach a different rubric to each part.

By submitting a demo student assignment, accessing the rubric manager and selecting the rubric manager under each part this seemed possible, however the Turnitin assignment reverted to the first rubric attached to the first part.

Is Turnitin considering the possibility of attaching more an 1 rubric to an assignment where there are multiple parts?

Regards
Anna

**Comment by amclarty** [comment]
I've made our product owner aware of your request. You can also raise this in UserVoice: https://turnitin.uservoice.com/

Please note that this repository is no longer updated. Any future requests should be raised in one of these repositories:

https://github.com/jmcgettrick/moodle-mod_turnitintooltwo
https://github.com/jmcgettrick/moodle-plagiarism_turnitin
https://github.com/jmcgettrick/moodle-block_turnitin

Thanks!
