### ISSUE TITLE
When grading group submissions to Moodle Assignment with PP, only the original uploader's grade is sent to Moodle grade book

### ISSUE THREAD

**Issue by alexumn** [jmcgettrick/MoodleDirectV2#59]
Platform: Moodle 2.6.4+ (Build: 20140731) with Turnitin Direct v2 plugin version 2014012405

Scenario: A Moodle Assignment is set to have students submit in groups and has the Turnitin Plagiarism Prevention plugin enabled. Teachers expect grades to apply to all group members.

Issue: When a group member makes a submission (and it is sent to Turnitin), the file appears for other group members as expected. However, when a teacher opens the Originality Report for any group member, then enters a score in the Turnitin Originality tab in the upper right (e.g. 51 OUT OF 100) and closes the window, the score is applied to the Moodle grade book, but only to the group member who originally submitted the file. So, if you clicked another group member's Originality Report link, the original submitter's submission appears. The score entered in that window does not apply to other group members.

What would be preferred: In cases where the Turnitin PP is used in Assignment groups, in the Originality window/tab, there should be a checkbox that is checked by default which says "Apply grade to entire group". This would be similar to behavior in the Moodle Assignment grading page for group submissions.

**Comment by jmcgettrick** [comment]
Hi Alex, this is now in the latest release. There is a bug in Moodle 2.8 though where user's grades only show in group submissions if they have submitted, that should be rectified soon though.
