### ISSUE TITLE
In PP plugin, only original group uploader can access Grademark and/or OR reports

### ISSUE THREAD

**Issue by alexumn** [jmcgettrick/MoodleDirectV2#60]
Platform: Moodle 2.6.4+ (Build: 20140731) with Turnitin Direct v2 plugin version 2014012405

Scenario: A Moodle Assignment is set to have students submit in groups and has the Turnitin Plagiarism Prevention plugin enabled. Teachers expect group submission Grademark and Originality Reports to be available to all group members. 

Issue: When a group member makes a submission (and it is sent to Turnitin), the file appears for other group members in the instructor submissions interface, as expected. However, when the Grademark link or Originality Report (optionally) appears to students, only the group member who originally submitted the assignment can access these reports. Other group members cannot see the OR link. When other group members click the Grademark icon, they get the error:

Sorry, we could not process your request

You are not authorized to access this resource.

**Comment by jmcgettrick** [comment]
Hi Alex, this is now in the latest release. We aren't able to show scores for text content submissions but file submissions are ok.
