### ISSUE TITLE
Split repositories by plugins

### ISSUE THREAD

**Issue by pjking07** [jmcgettrick/MoodleDirectV2#79]
Please consider splitting this repository into one per plugin (following the Moodle standard).

By creating one repository per plugin, other developers will be able to reference these plugins in their moodle repositories as submodules through git. As it stands, one cannot link to this project as a submodule.

[Moodle plugin template](https://github.com/moodlehq/moodle-mod_newmodule)
[Splitting a subfolder out into a new repository](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository)
Ref: <https://github.com/ip-pauldawson/MoodleDirect/pull/10>

**Comment by mattgibson** [comment]
+1

I raised this before, and it's still a real issue. This is the only one of 50 or so plugins we use which cannot be managed automatically using git submodules.

**Comment by dulldave** [comment]
+1

**Comment by jmcgettrick** [comment]
We've made a start on this, by moving the block element to a separate repository and including it as a submodule. Provided there are no problems around this we'll look at doing the same mod and plagiarism.

**Comment by sk-unikent** [comment]
@jmcgettrick Great! You can retain git history when doing this as mentioned above, e.g.
```
git clone git@github.com:jmcgettrick/MoodleDirectV2.git
cd MoodleDirectV2
git filter-branch --prune-empty --subdirectory-filter blocks/turnitin master
git remote add split git@github.com:jmcgettrick/moodle-block_turnitin.git
git push -f split master
```

**Comment by PeloNZ** [comment]
Hi John, any progress with this? It will be very helpful.

**Comment by jmcgettrick** [comment]
Thanks for that @PeloNZ - I can't do it straightaway but I'll get those requests merged in soon.

**Comment by brendanheywood** [comment]
FYI, we are working around this with a few sym links:

```
/third-party/MoodleDirectV2 <- actual submodule location
/third-party/MoodleDirectV2/config.php -> ../../config.php <- sym link
/mod/turnitintooltwo -> ../third-party/MoodleDirectV2/mod/turnitintooltwo/ <- sym link
/mod/turnitin -> ../third-party/MoodleDirectV2/plagiarism/turnitin/ <- sym link
```

This setup above works fine with most code that correctly uses $CFG->dirroot instead of ../../

However the unit tests barf, here's a patch to fix the tests:

https://github.com/marcusboon/moodle-r2/commit/a3711afbcab7e0bb6169789d1c7a1c23f475ef1e

btw we submitted this to HQ and they didn't want it :(

**Comment by brki** [comment]
I'm looking forward to this.  We'll have to make some workaround until these are split.

**Comment by hitteshahuja** [comment]
Hi John,
Any eta on the split of modules into different repos ? Would it help if we split it and give you the repositories to fork from ?

**Comment by jmcgettrick** [comment]
We're going to try and do this in the next week or so. The plagiarism plugin will still be dependent on the mod_turnitintooltwo code initially but we're going to work on making them completely independent of each other.

**Comment by jmcgettrick** [comment]
Apologies for the time this has taken but this has now been done. The 3 folders are now all in their own repositories:
- Direct v2: https://github.com/jmcgettrick/moodle-mod_turnitintooltwo
- Plagiarism plugin: https://github.com/jmcgettrick/moodle-plagiarism_turnitin
- Block: https://github.com/jmcgettrick/moodle-block_turnitin

The plagiarism plugin still has a dependency on the mod_turnitintooltwo for now but we are starting to migrate code over and hope to eliminate this dependency as soon as we can.

We'll keep this repository here for now but will be removing the code and changing the readme to point people at the new repositories.

Thanks for the help and apologies again!

John

**Comment by brki** [comment]
:+1:  Thanks!

**Comment by pjking07** [comment]
:trophy: :+1:

**Comment by danmarsden** [comment]
Thanks John - I don't think you need to eliminate the dependency between turnitintooltwo and the pp plugin - it's perfectly acceptable for you to include your core lib files within the module and leverage those from within the PP plugin - unless you think it makes it easier on your end to make them both independent. There are many other examples of this within the Moodle code-base where a core plugin contains all the main lib files and another plugin leverages those core files.
