### ISSUE TITLE
plagiarism_turnitin: check connection to TII API before calling get_accepted_user_agreement()

### ISSUE THREAD

**Issue by tonyjbutler** [jmcgettrick/MoodleDirectV2#91]
If a student tries to submit when a connection cannot be made to the Turnitin API (e.g. during periods of Turnitin maintenance downtime) they receive the error "Exception - couldn't connect to host" and the Moodle assignment submission page cannot fully load. For us, this defeats the object of using the plagiarism_turnitin plugin as opposed to Turnitin Direct, as submissions are still disrupted when the TII API is unavailable.

We have worked around this by adding a pre-check for the Turnitin API connection. If this returns false there is no attempt to call getAcceptedUserAgreement(), and the EULA link is not displayed. This allows the student to submit to Moodle and everything appears as normal, and the TII submission event will be queued in the Moodle events_queue database table until the TII connection is restored, at which point it will be submitted (or in the case of a student who has not yet accepted the EULA, it will remain in the queue until the student accepts, and will then be submitted).

Diff available at https://github.com/lucisgit/MoodleDirectV2/commit/c07501df729f348e3b2cc3771a50e05409ceddd9.

**Comment by jmcgettrick** [comment]
Thanks Tony, this has been fixed and is in the latest release.
