### ISSUE TITLE
Horizontal Scroll bar disappearing

### ISSUE THREAD

**Issue by mhughes2k** [jmcgettrick/MoodleDirectV2#96]
We have an issue where we have run a piece of javascript to putz with the Assignment table so that the scroll bar is at the window level and not inside the content area.

However with Turnitin enabled when the Tooltup pops up and then disappears the horizontal scroll bar disappears as well.

This looks like it may be a ToolTipster issue https://github.com/iamceege/tooltipster/issues/255 that is fixed in a forthcoming version.

Just really just a heads up and if anyone else has really wide mod_assign grading tables with window level scrolling it could be an issue there too.

M

**Comment by jmcgettrick** [comment]
Thanks Michael. We've made a note of this for when we upgrade tooltipster.
